//https://stackoverflow.com/questions/32786103/requirejs-text-plugin-and-underscorejs-templates
define([
	"module",
	"backbone"
],function(
	module,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(obj);
});
