//https://stackoverflow.com/questions/41699966/cubism-d3-dependency-with-requirejs
define([
	"module",
	"cubism"
],function(
	module,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(obj);
});
