define([
	'module',
	'jquery.dataTables',
	"dataTables.buttons",
	"dataTables.select",
	"dataTables.bootstrap"
],function(module,obj){
	console.log([module.id,'start'].join(':'));
	console.log(obj);
});
