/*
 * dojo load test - dojo require works different, thats one issue, and propper changes needs to be implemented for goja
 */
define([
	"module",
	//"dojo",
	"dojo/_base/config",
	"dojo/_base/array",
	"dojo/_base/query",
	"dojo/_base/Color",
],function(
	module,
	config,
	array,
	query,
	color
){
	console.log([module.id,'start'].join(':'));
	console.log(config);
	console.log(array);
	console.log(query);
	console.log(color);
});
