define([
	"module",
	"expect",
],function(
	module,
	expect
){
	console.log([module.id,'start'].join(':'));
	console.log(expect);
	window.expect=expect;
	console.log(expect(window.r).to.be(undefined));
	console.log(expect({ a: 'b' }).to.eql({ a: 'b' }))
	console.log(expect(5).to.be.a('number'));
	console.log(expect([]).to.be.an('array'));
	console.log(expect(window).not.to.be.an(Image));
	try{
		expect(42).to.be(24);
	}catch(e){
		console.error(e.toString());
	}
});
