define([
	"module",
	"cyclejs",
	"kwe.logger",
	"kwe.wslogger"
],function(
	module,
	cyclejs,
	Logger,
	WSLogger
){
	console.log([module.id,'start'].join(':'));
	console.log(cyclejs.decycle(Logger));
	console.log(cyclejs.decycle(WSLogger));
	var wslogger=new WSLogger();
	Logger.add("CON",console);
	Logger.add("WS",wslogger);
	console.log(cyclejs.decycle(Logger));
	for(var i=0;i<32;i++)
		Logger.log("test"+i);
	Logger.log(cyclejs.decycle(Logger));
	Logger.log(cyclejs.decycle(Logger));
	Logger.log(cyclejs.decycle(Logger));
	Logger.log(cyclejs.decycle(Logger));
	for(var i=0;i<32;i++)
		Logger.log("test"+i);
	Logger.log(cyclejs.decycle(Logger));
	Logger.log(require);
	Logger.log(require.s);
	Logger.log(Logger);
	Logger.log(module);
	Logger.log("XXX");
	Logger.log("XXX");
	Logger.log("XXX");
	Logger.remove("WS");
	Logger.log("YYY");
	Logger.log("YYY");
	Logger.log("YYY");
	Logger.remove("CON");
	Logger.add("WS",wslogger);
	Logger.log("ZZZ");
	Logger.log("ZZZ");
	Logger.log("ZZZ");
});
