//https://github.com/davidsonfellipe/lena.js/blob/master/lib/filters/saturation.js
//https://ourcodeworld.com/articles/read/515/how-to-add-image-filters-photo-effects-to-images-in-the-browser-with-javascript-using-lena-js
define([
	"module",
	"lenajs",
],function(
	module,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(obj);
});
