define([
	"module",
	"libsodium",
	"sodium",
],function(
	module,
	libsodium,
	sodium
){
	console.log([module.id,'start'].join(':'));
	console.log(libsodium);
	console.log(sodium);
	window.sodium=sodium;
	console.log(sodium.to_hex('abcdefg'));
	console.log(sodium.crypto_generichash(64,'lorem'));
});
