//https://github.com/pixijs/pixi.js/releases
//https://github.com/kittykatattack/learningPixi
define([
	"module",
	"pixijs",
],function(
	module,
	PIXI
){
	console.log([module.id,'start'].join(':'));
	console.log(PIXI);
	//verify
	let type="WebGL"
	if(!PIXI.utils.isWebGLSupported()){
		type="canvas"
	}
	PIXI.utils.sayHello(type)
	//create
	let app=new PIXI.Application({ 
		width:256,
		height:256,
		antialias:true,
		transparent:false,
		resolution:1
	});
	app.renderer.backgroundColor=0xFF0000;
	app.renderer.autoResize=true;
	app.renderer.resize(512,512);
	document.body.appendChild(app.view);
});
