//https://github.com/stephband/scribe
//https://cruncher.ch/blog/scribe/
define([
	"module",
	"scribe",
],function(
	module,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(obj);
});
