require([
	'console',
],function(console){
	//--console tests - begin
	console.time('foo');
	console.log('main:');
	console.count();
	console.count();
	console.count();
	console.count();
	console.count('foo');
	console.count('bar');
	console.count('foo');
	console.count('bar');
	console.count('bar');
	console.count('foo');
	console.count('bar');
	console.count('bar');
	console.count('bar');
	console.timeLog('foo');
	console.count('foo');
	console.count('bar');
	console.count('bar');
	console.count('bar');
	console.count('bar');
	console.countReset();
	console.countReset('foo');
	console.countReset('bar');
	console.countReset('baz');
	console.count('foo');
	console.count('bar');
	console.count('baz');
	console.timeLog('foo');
	console.timeEnd('foo');
	//--console tests - end
});
