/*
 * dojo load test - dojo require works different, thats one issue, and propper changes needs to be implemented for goja
 */

define([
	"module",
	"console",
	"window",
	"document",
],function(
	module,
	console,
	_window,
	_document
){
	try{
		console.log('----------------------------------------');
		console.log([module.id,'start'].join(':'));
		//bootstrap globals
		window=_window;
		document=_document;
		this.window=window;
		this.document=window;
		console.log('----------------------------------------');
		require([
			"module",
			"console",
			"dojo/_base/config",
			//"dojo/_base/configRhino",
			"dojo/_base/Color",
			"dojo/_base/json",
			"dojo/_base/array",
			"dojo/_base/url",
			"dojo/_base/lang",
			"dojo/_base/sniff",
			"dojo/_base/kernel",
			/*
			"dojo/_base/query",
Color.js
Deferred.js
NodeList.js
browser.js
configFirefoxExtension.js
configNode.js
configRhino.js
configSpidermonkey.js
connect.js
declare.js
event.js
fx.js
html.js
loader.js
query.js
unload.js
window.js
xhr.js
			*/
		],function(
			module,
			console,
			config,
			Color,
			json,
			array,
			//query,
		){
			console.log([module.id,'start'].join(':'));
		});

		println('done');
	}catch(e){console.error(e.toString());}
});
