define([
	"module",
	"console",
	"cyclejs",
	//"vendor/domino/index"
	"domino"
],function(
	module,
	console,
	cycle,
	domino
){
	console.log([module.id,'start'].join(':'));
	console.log(JSON.stringify(cycle.decycle(domino)));
	try{
		window=domino.createWindow("");
		document=window.document;
		console.log(document.documentElement.innerHTML);
		println(document.documentElement.innerHTML);
	}catch(e){
		console.error(e.toString());
	}
});
