define([
	"module",
	"console",
	"request"
],function(
	module,
	console,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(typeof(obj));
	console.log(JSON.stringify(obj.tojson()));
	request.ResponseHeader().Set("Content-Type","application/json");//request.ResponseHeader().Set("Content-Type","image/svg+xml");
	print(JSON.stringify(obj.tojson()));
});
