define([
	"module",
	"console",
	"node",
	"document",
	"window",
	"canvas",
	"html",
],function(
	module,
	console,
	node,
	document,
	window,
	canvas,
	html
){
	console.log([module.id,'start'].join(':'));
	console.log(typeof(node));
	console.log(typeof(canvas));
	console.log(typeof(html));
	console.log(typeof(document));
	console.log(typeof(window));
});
