define([
	"goja/module",
	"goja/console",
	"goja/node",
	"goja/document",
	"goja/window",
	"goja/canvas",
	"goja/html",
],function(
	module,
	console,
	node,
	document,
	window,
	canvas,
	html
){
	console.log([module.id,'start'].join(':'));
	console.log(typeof(node));
	console.log(typeof(canvas));
	console.log(typeof(html));
	console.log(typeof(document));
	console.log(typeof(window));
});
