//color library
//https://github.com/francisrstokes/kandinsky-js
//skullquake: in progress of converting to es5...
define([
	"module",
	"console",
	"kandinsky",
],function(
	module,
	console,
	kandinsky
){
	console.log([module.id,'start'].join(':'));
	console.log(kandinsky);
console.log(kandinsky.hex2rgb("#FF0000"));
console.log(kandinsky.rgb2hex([255,0,0]));
console.log(kandinsky.rgb2hsl([255,0,0]));
console.log(kandinsky.hsl2rgb([1,1,0.5]));
console.log(kandinsky.hex2hsl("#FF0000"));
console.log(kandinsky.hsl2hex([1,1,0.5]));
console.log(kandinsky.lightenHex(0.5,"#888888"));
console.log(kandinsky.darkenHex(0.5,"#888888"));
console.log(kandinsky.lightenRgb(0.5,[128,128,128]));
console.log(kandinsky.darkenRgb(0.5,[128,128,128]));
console.log(kandinsky.lightenHsl(0.5,[1,1,0.5]));
console.log(kandinsky.darkenHsl(0.5,[1,1,0.5]));
console.log(kandinsky.lerp3(0.5,[1,2,3],[1,4,6]));
console.log(kandinsky.linearGradient(10,[1,2,3],[1,4,6]));
console.log(kandinsky.gradient(function(i){return i;},10,[1,2,3],[1,4,6]));
	/*
,
multiGradient,
rLinearGradient,
rGradient,
rMultiGradient,
complimentRgb,
complimentHex,
complimentHsl,
rgb2css,
hsl2css,
polute
	*/
});
