//https://github.com/pieroxy/lz-string/tree/master/libs
define([
	"module",
	"console",
	"lzstring",
],function(
	module,
	console,
	LZString
){
	console.log([module.id,'start'].join(':'));
	console.log(LZString);
	{
		original="0123456789abcdef";
		inflated=LZString.compress(original);
		deflated=LZString.decompress(inflated);
		console.log(original);
		console.log(inflated);
		console.log(deflated);
		println(original);
		println(inflated);
		println(deflated);
	}
	{
		original="0123456789abcdef";
		inflated=LZString.compressToBase64(original);
		deflated=LZString.decompressFromBase64(inflated);
		console.log(original);
		console.log(inflated);
		console.log(deflated);
		println(original);
		println(inflated);
		println(deflated);
	}
	{
		original="0123456789abcdef";
		inflated=LZString.compressToUTF16 (original);
		deflated=LZString.decompressFromUTF16 (inflated);
		console.log(original);
		console.log(inflated);
		console.log(deflated);
		println(original);
		println(inflated);
		println(deflated);
	}
	{
		original="0123456789abcdef";
		inflated=LZString.compressToUint8Array(original);
		deflated=LZString.decompressFromUint8Array(inflated);
		console.log(original);
		console.log(inflated);
		console.log(deflated);
		println(original);
		println(JSON.stringify(inflated));
		println(deflated);
	}
});
