define([
	"module",
	"cyclejs",
	"r"
],function(
	module,
	cyclejs,
	r
){
	request.ResponseHeader().Set("Content-Type","text/plain");
	println([module.id,"start"].join(":"));
	println(typeof(r));
	println([module.id,"end"].join(":"));
});
