define([
	"module",
	"console",
	"request"
],function(
	module,
	console,
	obj
){
	console.log([module.id,'start'].join(':'));
	console.log(typeof(obj));
	request.ResponseHeader().Set("Content-Type","text/html");//request.ResponseHeader().Set("Content-Type","image/svg+xml");
	print(JSON.stringify(obj.tojson()));
});
