define(["module"],function(module){
	var baseUrl="/kweutils/lib";
	var modPath="";
	var GOJA=true;
	var dojoConfig = {
		baseUrl:"./www/kweutils/",
		async: 0, // We want to make sure we are using the "modern" loader
		hasCache: {
			"host-node": 1, // Ensure we "force" the loader into Node.js mode
			"dom": 0 // Ensure that none of the code assumes we have a DOM
		},
		// While it is possible to use config-tlmSiblingOfDojo to tell the
		// loader that your packages share the same root ath as the loader,
		// this really isn't always a good idea and it is better to be
		// explicit about our package map.
		packages: []
	};//will read?

	requirejs.config({
		"waitSeconds":0,
		//"baseUrl":"./lib",
		"baseUrl":baseUrl,
		"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"paths":{
			"testdata":modPath+"data",
			"env":modPath+"goja/env",//goja compat
			"Phaser":modPath+"vendor/phaser/3.50.0/phaser.min",
			"Phaser3220":modPath+"vendor/phaser/3.22.0/phaser-arcade-physics.min",
			"console":modPath+"goja/console",//goja compat
			"pubsub":modPath+"goja/pubsub",
			"pathutils":modPath+"goja/pathutils",
			"idutils":modPath+"goja/idutils",//goja compat
			"window":modPath+"goja/window",//domino wrap
			"document":modPath+"goja/document",//domino wrap
			"request":modPath+"goja/request",//goja compat
			"xlsx":modPath+"vendor/sheetjs/xlsx.full.min",//not getting this to work
			"colorutils":modPath+"goja/colorutils",
			"pdfjs":modPath+"vendor/pdfjs/pdf",//not getting this to work
			"js-dos":modPath+"vendor/js-dos/js-dos",
			"jsnes":modPath+"vendor/jsnes/jsnes.min",
			"ace":modPath+"vendor/ace/ace",
			"babylonjs":modPath+"vendor/BabylonJS/babylon",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"jspanelcss":modPath+"vendor/jspanel/jspanelcss",//add css
			"jspanel":modPath+"vendor/jspanel/jspanel",
			"jspanel.dock":modPath+"vendor/jspanel/jspanel.dock",
			"jspanel.contextmenu":modPath+"vendor/jspanel/jspanel.contextmenu",
			"jquery.terminal":modPath+"vendor/jqueryterminal/jquery.terminal-2.19.2",
			"jquery.player":modPath+"vendor/jquery.jplayer/jquery.jplayer.min",
			"wcwidth":modPath+"vendor/jqueryterminal/wcwidth",
			"ascii_table":modPath+"vendor/jqueryterminal/ascii_table",
			"autocomplete_menu":modPath+"vendor/jqueryterminal/autocomplete_menu",
			"unix_formatting":modPath+"vendor/jqueryterminal/unix_formatting",
			"xml_formatting":modPath+"vendor/jqueryterminal/xml_formatting",
			"class":modPath+"vendor/classjs/class.min",
			"classjs":modPath+"vendor/classjs/class.min",
			"css":modPath+"vendor/requirecss/css.min",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"jquery.jsonForm":modPath+"vendor/jsonform/jsonform",
			"jsv":modPath+"vendor/jsv/jsv",
			"bootstrap":modPath+"vendor/bootstrap/3.3.7/bootstrap.min",
			"jquery.dataTables.css":modPath+"vendor/datatables/1.10.22/jquery.dataTables.css",
			"jquery.dataTables":modPath+"vendor/datatables/1.10.22/jquery.dataTables.min",
			"dataTables.bootstrap":modPath+"vendor/datatables/1.10.22/dataTables.bootstrap.min",
			"dataTables.responsive":modPath+"vendor/datatables/1.10.22/dataTables.responsive.min",
			"dataTables.rowGroup":modPath+"vendor/datatables/extensions/rowgroup/1.1.2/dataTables.rowGroup.min",
			"dataTables.searchPanes":modPath+"vendor/datatables/extensions/searchpanes/1.2.1/dataTables.searchPanes.min",
			"dataTables.keyTable":modPath+"vendor/datatables/extensions/keytable/2.5.3/dataTables.keyTable.min",
			"buttons.colVis":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.colVis.min",
			"buttons.flash":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.flash.min",
			"buttons.print":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.print.min",
			"buttons.html5":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.html5.min",
			"dataTables.buttons":modPath+"vendor/datatables/extensions/buttons/1.6.5/dataTables.buttons.min",
			"dataTables.colReorder":modPath+"vendor/datatables/extensions/colreorder/1.5.3/dataTables.colReorder.min",
			"dataTables.autoFill":modPath+"vendor/datatables/extensions/autofill/2.3.5/dataTables.autoFill.min",
			"dataTables.fixedColumns":modPath+"vendor/datatables/extensions/fixedcolumns/3.3.2/dataTables.fixedColumns.min",
			"dataTables.rowReorder":modPath+"vendor/datatables/extensions/rowreorder/dataTables.rowReorder.min",
			"dataTables.fixedHeader":modPath+"vendor/datatables/extensions/fixedheader/3.1.7/dataTables.fixedHeader.min",
			"dataTables.select":modPath+"vendor/datatables/extensions/select/1.3.1/dataTables.select.min",
			"dataTables.responsive":modPath+"vendor/datatables/extensions/responsive/2.2.6/dataTables.responsive.min",
			"ace":modPath+"vendor/ace/ace",
			"babel":modPath+"vendor/babel/babel.min",
			"spectrum":modPath+"vendor/spectrum/spectrum",
			"text":modPath+"vendor/requirejs/require.text",
			"backbone":modPath+"vendor/backbone/1.4.0/backbone-min",
			"backbone.localstorage":modPath+"vendor/backbone/plugins/Backbone.localStorage/2.0.0/backbone.localStorage",
			"babel-plugin-transform-remove-strict-mode":modPath+"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":modPath+"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":modPath+"vendor/es6/es6",
			"vuejs":modPath+"vendor/vuejs/2.6.12/vue.min",
			"vue-router":modPath+"vendor/vue-router/3.4.9/vue-router.min",
			"d3-3.5.17":modPath+"vendor/d3/3.5.17/d3.v3.min",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			"d3":modPath+"vendor/d3/4.13.0/d3.v4.min",
			//"d3":modPath+"vendor/d3/6.3.1/d3.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.1/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.2/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.3/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.5/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.7/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.8/d3-3d.min",
			"d3-3d":modPath+"vendor/d3-3d/0.0.9/d3-3d.min",
			"d3-array":modPath+"vendor/d3-array/1.2.1/d3-array.min",
			"d3-collection":modPath+"vendor/d3-collection/1.0.4/d3-collection.min",
			"d3-dispatch":modPath+"vendor/d3-dispatch/1.0.3/d3-dispatch.min",
			"d3-request":modPath+"vendor/d3-request/1.0.6/d3-request.min",
			"d3-scale-chromatic":modPath+"vendor/d3-scale-chromatic/d3-scale-chromatic.v1.min",
			"d3-selection":modPath+"vendor/d3-selection/1.1.0/d3-selection.min",
			//"domino":modPath+"vendor/domino/blocks/index",
			"domino":modPath+"vendor/domino/domino",
			//https://stackoverflow.com/questions/18176737/svg-js-plugins-and-requirejs
			"svg":modPath+"vendor/svg.js/3.0.16/svg.min",
			"zest":modPath+"vendor/zest/zest",
			//"axios":modPath+"vendor/axios/0.12.0/axios.min",
			"axios":modPath+"vendor/axios/0.21.0/axios",
			"cyclejs":modPath+"vendor/cyclejs/cycle",
			"jsbasic":modPath+"vendor/jsbasic/basic",
			"jsbasic.tty":modPath+"vendor/jsbasic/tty",
			"jsbasic.dos":modPath+"vendor/jsbasic/dos",
			"jsbasic.lores":modPath+"vendor/jsbasic/lores",
			"jsbasic.hires":modPath+"vendor/jsbasic/hires",
			"jsbasic.bell":modPath+"vendor/jsbasic/bell",
			"jsbasic.keyboard":modPath+"vendor/jsbasic/keyboard",
			"cubism":modPath+"vendor/cubism/1.6.0/cubism.v1",
			"LoremIpsum":modPath+"vendor/lorem/lorem",
			"tonejs":modPath+"vendor/tonejs/14.7.74/Tone",
			"snap":modPath+"vendor/snap.svg/0.5.0/snap.svg-min",
			"bonsai":modPath+"vendor/bonsai/0.4.1/bonsai-0.4.1.min",
			"carbon":modPath+"vendor/carbon/C.min",
			/*
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.1",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.2",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.0",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.1",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.3.0",
			"svidget":modPath+"vendor/svidget/0.3.5/svidget",
			 */
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.2",
			"pablo":modPath+"vendor/pablo/0.5.2/pablo",
			"pts":modPath+"vendor/pts/0.9.1/pts",
			"anime":modPath+"vendor/anime/3.2.0/anime.min",
			"twojs":modPath+"vendor/twojs/1.1/two.min",
			"zdog":modPath+"vendor/zdog/1.1.2/zdog.dist.min",
			"pixijs":modPath+"vendor/pixijs/6.0.0/pixi.min",
			"tweenjs":modPath+"vendor/tweenjs/18.6.4/tween.amd",
			"mathjax":modPath+"vendor/mathjax/3.1.2/tex-mml-chtml",
			//"dojo":modPath+"vendor/dojo/1.16.3/dojo/dojo",
			//"dojo":modPath+"vendor/dojo/1.16.3/dojo/dojo",
			"vexflow":modPath+"vendor/vexflow/3.0.9/vexflow-min",
			"scribe":modPath+"vendor/scribe/js/scribe",
			"p5":modPath+"vendor/p5/1.2.0/p5",
			"mathjs":modPath+"vendor/mathjs/8.1.1/math",
			"terrajs":modPath+"vendor/terrajs/2.4.1/terra.min",
			"bignumber":modPath+"vendor/bignumber/bignumber",
			"sylvester":modPath+"vendor/sylvester/0.1.3/sylvester.src",
			"numeric":modPath+"vendor/numeric/1.2.6/numeric",
			"jstat":modPath+"vendor/jstat/1.9.4/jstat.min",
			"science":modPath+"vendor/science/1.9.3/science.v1",
			"rift":modPath+"vendor/rift/0.1.2/rift",
			"lexer":modPath+"vendor/lexer/1.7.8/lexer",
			//"jison":modPath+"vendor/jison/0.3.10/jison",
			"jison":modPath+"vendor/jison/jison",
			//"xregexp":modPath+"vendor/xregexp/3.2.0/xregexp-all.min",
			"xregexp":modPath+"vendor/xregexp/4.4.1/xregexp-all",
			"sjcl":modPath+"vendor/sjcl/1.0.8/sjcl",
			"jsencrypt":modPath+"vendor/jsencrypt/3.0.0/jsencrypt",
			"openpgp":modPath+"vendor/openpgp/4.10.9/openpgp",
			//"openpgp":modPath+"vendor/openpgp/4.10.9/lightweight/openpgp",//...ugh
			//"forge":modPath+"vendor/forge/0.10.0/forge",//still have to sort out amd
			"forge":modPath+"vendor/forge/0.7.0/forge.min",
			"crypto":modPath+"vendor/cryptojs/4.0.0/crypto-js",
			"libsodium":modPath+"vendor/libsodiumjs/0.7.8/libsodium",
			"sodium":modPath+"vendor/libsodiumjs/0.7.8/libsodium-wrappers",
			"victorjs":modPath+"vendor/victorjs/1.1.0/victor",
			"vecla":modPath+"vendor/vecla/vec.amd",
			"kandinsky":modPath+"vendor/kandinskijs/1.3.0/kandinsky",
			"chroma":modPath+"vendor/chroma/2.1.0/chroma",
			"tinycolor":modPath+"vendor/tinycolor/1.4.2/tinycolor",
			//"jshint":modPath+"vendor/jshint/2.12.0/jshint",
			"jshint":modPath+"vendor/jshint/2.6.3/jshint",
			"mocha":modPath+"vendor/mocha/8.2.1/mocha",
			"chai":modPath+"vendor/chai/4.2.0/chai.min",
			"chai-match":modPath+"vendor/chai/chai-match/1.1.1/chai-match",
			"chai-jq":modPath+"vendor/chai/chai-jq/0.0.9/chai-jq.min",
			"jasmine":modPath+"vendor/jasmine/2.3.0/jasmine-core/jasmine",
			"jasmine-boot":modPath+"vendor/jasmine/2.3.0/jasmine-core/boot",
			"jasmine-html":modPath+"vendor/jasmine/2.3.0/jasmine-core/jasmine-html",
			"brython":modPath+"vendor/brython/3.8.0/brython.min",
			"brython_stdlib":modPath+"vendor/brython/3.8.0/brython_stdlib",
			"threejs":modPath+"vendor/threejs/r71/three",
			"qunit":modPath+"vendor/qunit/2.13.0/qunit",
			"tape":modPath+"vendor/tape/4.4.0/tape",
			"perljs":modPath+"vendor/perljs/perl",
			"sinon":modPath+"vendor/sinon/9.2.2/sinon-no-sourcemaps",
			"expect":modPath+"vendor/expect/0.3.1/expect",
			"should":modPath+"vendor/should/3.3.2/should.min",
			"escodegen":modPath+"vendor/escodegen/2.0.0/escodegen",
			"estraverse":modPath+"vendor/estraverse/5.2.0/estraverse",
			//"esutils":modPath+"vendor/esutils/2.0.3/utils",
			"esutils":modPath+"vendor/esutils/2.0.3/index",
			"esprima":modPath+"vendor/esprima/2.7.3/esprima",
			"dukweb":modPath+"vendor/dukweb/dukweb",
			"jslint":modPath+"vendor/jslint/jslint",
			"acorn":modPath+"vendor/acorn/7.3.1/acorn",
			"cdecl":modPath+"vendor/cdecl/1.0.0/cdecl",
			"route-parser":modPath+"vendor/route-parser/0.0.5/index",
			"mustache":modPath+"vendor/mustache/4.1.0/mustache.min",
			"handlebars":modPath+"vendor/handlebars/4.7.6/handlebars.amd.min",
			"nunjucks":modPath+"vendor/nunjucks/3.2.2/nunjucks.min",
			"hoganjs":modPath+"vendor/hoganjs/3.0.2/hogan.min.amd",
			"doT":modPath+"vendor/doT/1.1.1/doT",
			"lenajs":modPath+"vendor/lenajs/lena.amd",
			"bitset":modPath+"vendor/bitset/5.1.1/bitset.min",
			"jsfs":modPath+"vendor/jsfs/jsfs",
			"lzstring":modPath+"vendor/lz-string/1.4.4/lz-string",
			"base64string":modPath+"vendor/lz-string/1.4.4/base64-string",
			"randomjs":modPath+"vendor/random-js/2.0.0/random.min",
			"immutablejs":modPath+"vendor/immutable-js/3.8.2/immutable.min",
			"mori":modPath+"vendor/mori/0.3.2/mori.min",
			"buckets":modPath+"vendor/buckets-js/1.98.2/buckets.min",
			"hashmapjs":modPath+"vendor/hashmapjs/2.4.0/hashmap",
			"moment":modPath+"vendor/momentjs/moment.min",
			"moment-timezone":modPath+"vendor/moment-timezone/0.5.32/moment-timezone",
			"moment-timezone-utils":modPath+"vendor/moment-timezone/0.5.32/moment-timezone-utils",
			"date":modPath+"vendor/date/0.3.3/date.min",
			"msjs":modPath+"vendor/msjs/index",
			"fecha":modPath+"vendor/fetcha/4.0.0/fecha.min",
			"dayjs":modPath+"vendor/dayjs/1.10.2/dayjs.min",
			"date-fns":modPath+"vendor/date-fns/1.30.1/date_fns.min",
			"voca":modPath+"vendor/voca/1.4.0/voca.min",
			"selecting":modPath+"vendor/selecting/0.0.8/selecting.min",
			"underscore.string":modPath+"vendor/underscore.string/3.3.4/underscore.string.min",
			"sprintf":modPath+"vendor/sprintf/1.1.2/sprintf.min",
			"sugarjs":modPath+"vendor/sugarjs/2.0.4/sugar.min",
			//"locutus":modPath+"vendor/locutus/index",//todo//https://locutus.io/
			"he":modPath+"vendor/he/1.2.0/he",
			"URI":modPath+"vendor/URI/1.19.5/URI",
			"urljs":modPath+"vendor/urljs/2.3.4/url",
			"url-pattern":modPath+"vendor/url-pattern/url-pattern",
			"stringjs":modPath+"vendor/stringjs/3.3.3/string.min",
			"numeraljs":modPath+"vendor/numeraljs/2.0.6/numeral",
			"chancejs":modPath+"vendor/chancejs/1.1.7/chance.min",
			"accountingjs":modPath+"vendor/accountingjs/0.4.2/accounting.min",
			"odometer":modPath+"vendor/odometer/0.4.7/odometer.amd",
			"fraction":modPath+"vendor/fractionjs/4.0.12/fraction.min",
			"complex":modPath+"vendor/complexjs/2.0.11/complex.min",
			"quaternion":modPath+"vendor/quaternion/1.1.0/quaternion.min",
			"polynomial":modPath+"vendor/polynomialjs/1.4.5/polynomial",
			"ramda":modPath+"vendor/ramda/0.25.0/ramda.min",
			"rambda":modPath+"vendor/rambda/0.27.1/ramda.min",
			"mout":modPath+"vendor/mout/1.2.2",
			//"prelude":modPath+"vendor/prelude/0.4.2/index",//in progress
			//"preludels":modPath+"vendor/preludels/1.6.0/prelude-browser",//in progress
			"storejs":modPath+"vendor/storejs/2.0.12/store.everything.min",
			"localforage":modPath+"vendor/localforage/1.9.0/localforage",
			"jstorage":modPath+"vendor/jstorage/0.4.13/jstorage.min",
			"cross-storage.client":modPath+"vendor/cross-storage/1.0.0/client",
			"cross-storage.hub":modPath+"vendor/cross-storage/1.0.0/hub",
			"basketjs":modPath+"vendor/basketjs/0.5.2/basket.full.min",
			"bagjs":modPath+"vendor/bagjs/3.0.0/bag",
			"basil":modPath+"vendor/basil/basil.min",
			"js-cookie":modPath+"vendor/js-cookie/2.2.1/js.cookie-2.2.1.min",
			"dbjs":modPath+"vendor/dbjs/0.15.0/db.min",
			"lawnchair":modPath+"vendor/lawnchair/0.6.4/Lawnchair",
			"sqljs":modPath+"vendor/sqljs/1.4.0/sql-wasm",
			"crumbsjs":modPath+"vendor/crumbsjs/crumbs",
			"i18next":modPath+"vendor/i18next/19.8.4/i18next",
			"babelfish":modPath+"vendor/babelfish/1.2.0/babelfish",
			"ttag":modPath+"vendor/ttag/1.7.23/ttag",
			"async":modPath+"vendor/async/2.3.0/async",
			"q":modPath+"vendor/q/1.5.1/q",
			"step":modPath+"vendor/step/1.0.0/step",
			"contra":modPath+"vendor/contra/1.9.4/contra.min",
			"bluebird":modPath+"vendor/bluebird/3.5.0/bluebird.min",
			"bluebird.core":modPath+"vendor/bluebird/3.5.0/bluebird.core.min",
			"objecteventtarget":modPath+"vendor/objecteventtarget/ObjectEventTarget",
			"sporadic":modPath+"vendor/sporadic/0.3.0/sporadic.amd",
			"director":modPath+"vendor/director/1.2.6/director.min",
			"pagejs":modPath+"vendor/pagejs/1.11.6/page",
			"pathjs":modPath+"vendor/pathjs/0.8.4/path.min",
			"navaid":modPath+"vendor/navaid/1.2.0/navaid.min",
			"dompurify":modPath+"vendor/dompurify/2.2.6/purify.min",
			"js-xss":modPath+"vendor/js-xss/1.0.8/xss.min",
			"log":modPath+"vendor/log/0.3.0/log.min",
			"conzole":modPath+"vendor/conzole/0.1/conzole",
			"consolelog":modPath+"vendor/console.log-wrapper/2.1.3/consolelog.min",
			"loglevel":modPath+"vendor/loglevel/1.7.1/loglevel.min",
			"minilog":modPath+"vendor/minilog/3.1.0/minilog",
			"bottleneck":modPath+"vendor/bottleneck/2.19.5/es5",
			"oauthsignature":modPath+"vendor/oauth-signature/1.5.0/oauth-signature.min",
			"wretch":modPath+"vendor/wretch/1.7.4/wretch",
			"tracking":modPath+"vendor/trackingjs/1.1.2/tracking",//-min",
			"tracking.eye":modPath+"vendor/trackingjs/1.1.2/data/eye",//-min",
			"tracking.face":modPath+"vendor/trackingjs/1.1.2/data/face",//-min",
			"tracking.mouth":modPath+"vendor/trackingjs/1.1.2/data/mouth",//-min",
			"convnetjs":modPath+"vendor/convnetjs/convnet-min",
			"brainjs":modPath+"vendor/brainjs/2.0.0/brain-browser",
			"synapses":modPath+"vendor/synapses/7.3.1/synapses-opt",
			"bowser":modPath+"vendor/bowser/1.9.4/bowser.min",
			"benchmarkjs":modPath+"vendor/benchmarkjs/2.1.4/benchmark",
			"mprogress":modPath+"vendor/mprogress/0.1.1/mprogress.min",
			"nprogress":modPath+"vendor/nprogress/0.2.0/nprogress",
			"spinjs":modPath+"vendor/spinjs/4.1.0/spin.umd",
			"progressjs":modPath+"vendor/progressjs/0.1.0/progress.min",
			"progressbarjs":modPath+"vendor/progressbarjs/1.1.0/progressbar.min",
			"pace":modPath+"vendor/pace/1.2.3/pace.min",
			"topbar":modPath+"vendor/topbar/0.1.3/topbar.min",
			"nanobar":modPath+"vendor/nanobar/0.4.2/nanobar.min",
			"ladda":modPath+"vendor/ladda/2.0.1/ladda.amd",
			"parsleyjs":modPath+"vendor/parsleyjs/2.9.2/parsley.min",
			"platform":modPath+"vendor/platformjs/1.3.6/platform",
			"validator":modPath+"vendor/validatorjs/13.5.1/validator.min",
			"validatejs":modPath+"vendor/validatejs/2.0.1/validate.min",
			"isjs":modPath+"vendor/isjs/0.9.0/is.min",
			"fieldval":modPath+"vendor/fieldval/0.5.1/fieldval.min",
			"keypress":modPath+"vendor/keypress/2.1.5/keypress-2.1.5.min",
			"keyboardjs":modPath+"vendor/keyboard.js/keyboard.min",
			"zepto":modPath+"vendor/zepto/zepto",
			"ionrangeslider":modPath+"vendor/ion.rangeslider/2.3.1/ion.rangeSlider.min",
			"fancyinput":modPath+"vendor/fancyinput/1.2.0/fancyInput",
			"introjs":modPath+"vendor/introjs/2.9.3/intro.min",
			"tether":modPath+"vendor/tetherjs/1.4.7/tether.min",
			"shepherdjs":modPath+"vendor/shepherd/1.8.1/shepherd.min",
			"chardin":modPath+"vendor/chardin/0.2.0/chardinjs.min",
			"pageguide":modPath+"vendor/pageguide/1.3.2/pageguide.min",
			"hopscotch":modPath+"vendor/hopscotch/0.3.1/js/hopscotch_amd.min",
			"jquery.joyride":modPath+"vendor/joyride/2.0.0/jquery.joyride-2.1",
			"jquery.focusable":modPath+"vendor/focusable/1.0.0/focus-element-overlay.min",
			"driverjs":modPath+"vendor/driverjs/0.9.7/driver.min",
			"izitoast":modPath+"vendor/izitoast/1.4.0/iziToast.min",
			"messanger":modPath+"vendor/messanger/1.5.0/js/messenger.min",
			"noty":modPath+"vendor/noty/3.1.4/noty",
			"pnotify":modPath+"vendor/pnotify/5.2.0/node_modules/@pnotify/core/dist/PNotify",
			"toastr":modPath+"vendor/toastr/2.1.4/toastr.min",
			"humanejs":modPath+"vendor/humanejs/3.2.2/humane.min",
			"smokejs":modPath+"vendor/smokejs/smoke.amd.min",
			"notie":modPath+"vendor/notie/4.3.0/notie.min",
			//"":modPath+"",
		},
		"packages":[
			{
				"name":"dojo",
				"location":"vendor/dojo/1.16.3/dojo"
			}
		],

		"config":{
			"text":{
				//"env":"goja"
				"env":"xhr"
			}
		},
		"map":{
			"*":{
				//"jquery":"jquery-private"
				"datatables.net":"jquery.dataTables",                                                                                                                                     //https://datatables.net/forums/discussion/43169/unable-to-get-buttons-1-3-2-to-work-with-require-js-and-backbone-marionette
				"datatables.net-buttons":"dataTables.buttons"
			},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"xlsx":{
				"deps":[],
				"exports":"XLSX"//XLS too
			},
			"pdfjs":{//not gettings this to work
				"deps":[],
				"exports":"pdfjs-dist/build/pdf"//PDFNetworkStream"
			},
			"js-dos":{
				"deps":[],
				"exports":"Dos"
			},
			"jsnes":{
				"deps":[],
				"exports":"jsnes"
			},
			"jquery.player":{
				"deps":["jquery"],
				"exports":"jQuery.jPlayer"
			},
			"babylonjs":{
				"deps":[],
				"exports":"babylonjs"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"classjs":{
				"deps":[],
				"exports":"Class"
			},
			"class":{
				"deps":[],
				"exports":"Class"
			},

			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":["jspanelcss"],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"jquery.terminal":{
				"deps":["jquery","ascii_table",]
			},
			"wcwidth":{
				"deps":[]
			},
			"ascii_table":{
				"deps":["wcwidth"]
			},
			"autocomplete_menu":{
				"deps":["jquery","jquery.terminal"]
			},
			"unix_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"xml_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"browserify-shim":{
				"jquery":"global:jQuery"
			},
			"jquery.hotkeys":{
				"deps":["jquery"]//,
				//"exports":"jquery.hotkeys"
			},
			"jquery.easing":{
				"deps":["jquery"]
			},
			"kweui":{
				"deps":["jquery","jspanel"]
			},
			"ug-theme-default":{
				"deps":["jquery.unite","jquery.easing"]
			},
			"jquery.unite":{
				"deps":["jquery","jquery.easing"]
			},
			"bootstrap":{
				"deps":["jquery"]
			},
			"jquery.dataTables.css":{
				"deps":["jquery"]
			},
				//"deps":["jquery","jquery.dataTables.css"],//css!/medias/css/dataTable.css
			"jquery.dataTables":{
				"deps":[
					"jquery",
					"jquery.dataTables.css",//custom css injector
					//"css!./js/vendor/datatables/jquery.dataTables.min.css",
					//"css!./js/vendor/datatables/1.10.22/responsive.bootstrap.min.css",
					//"css!./js/vendor/datatables/1.10.22/dataTables.bootstrap.min.css",

				],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":[
					"jquery.dataTables",
					"jquery-private",
					/*
					"dataTables.buttons",
					"dataTables.responsive",
					"dataTables.rowGroup",
					"dataTables.searchPanes",
					"dataTables.keyTable",
					"buttons.colVis",
					"buttons.flash",
					"buttons.print",
					"buttons.html5",
					"dataTables.colReorder",
					"dataTables.autoFill",
					"dataTables.fixedColumns",
					"dataTables.rowReorder",
					"dataTables.fixedHeader",
					"dataTables.select",
					"dataTables.responsive",
					*/
				],
				"exports":"datatables"
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowGroup":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.searchPanes":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.keyTable":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.colVis":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.flash":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.print":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.html5":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.buttons":{
				//"deps":["jquery"],
				"deps":[
					"jquery",
					"datatables.net",
					//"buttons.colVis",
					//"buttons.flash",
					//"buttons.print",
					//"buttons.html5",
				],
			},
			"dataTables.colReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.autoFill":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedColumns":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedHeader":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.select":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"babel":{
				"deps":[],
				"exports":"Babel"
			},
			"backbone":{
				"deps":["underscore"],
				"exports":"Backbone"
			},
			"backbone.localstorage":{
				"deps":["underscore","backbone"],
				"exports":"Backbone.LocalStorage"
			},
			"es6":{
				"deps":["babel","text"]
			},
			"vue-router":{
				"deps":["vuejs"]
			},
			"d3-3.5.17":{
				//"deps":[],
				"exports":"d3"
			},
			"d3":{
				//"deps":[],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"console":{
				"deps":[],
				"exports":"console"
			},
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"svg":{
				"deps":[],
				"exports":"SVG"
			},
			"axios":{
				"deps":[],
				"exports":"axios"
			},
			"Phaser":{
				"exports":"Phaser"
			},
			"Phaser3220":{
			},
			"cubism":{
				"deps":["d3-3.5.17"],
				"exports":"cubism"
			},
			"LoremIpsum":{
				"deps":[],
				"exports":"LoremIpsum"
			},
			"bonsai":{
				"deps":[],
				"exports":"bonsai"
			},
			"carbon":{
				"deps":[],
				"exports":"C"
			},
			"svidget":{
				"deps":[],
				"exports":"svidget"
			},
			"pablo":{
				"deps":[],
				"exports":"Pablo"
			},
			"pts":{
				"deps":[],
				"exports":"Pts"
			},
			"pts":{
				"deps":[],
				"exports":"anime"
			},
			"twojs":{
				"deps":[],
				"exports":"Two"
			},
			"zdog":{
				"deps":[],
				"exports":"Zdog"
			},
			"pixijs":{
				"deps":[],
				"exports":"PIXI"
			},
			"mathjax":{
				"deps":[],
				"exports":"MathJax"
			},
			"p5":{
				"deps":[],
				"exports":"p5"
			},
			"terrajs":{
				"deps":[],
				"exports":"terra"
			},
			"bignumber":{
				"deps":[],
				"exports":"BigNumber"
			},
			"sylvester":{
				"deps":[],
				"exports":"Sylveste"
			},
			"numeric":{
				"deps":[],
				"exports":"numeric"
			},
			"jstat": {
				"deps":[],
				"exports": ["j$", "jStat"],
				"init":function(){//???
					return{
						"j$":j$,
						"jStat":jStat
					};
				}
			},
			"science":{
				"deps":[],
				"exports":"science"
			},
			"rift":{
				"deps":[],
				"exports":"Rift"
			},
			"lexer":{
				"deps":[],
				"exports":"Lexer"
			},
			"jison":{
				"deps":[],
				"exports":"Jison"
			},
			"xregexp":{
				"deps":[],
				"exports":"XRegExp"
			},
			"sjcl":{
				"deps":[],
				"exports":"sjcl"
			},
			"jsencrypt":{
				"deps":[],
				"exports":"JSEncrypt"
			},
			"openpgp":{
				"deps":[],
				"exports":"openpgp"
			},
			"forge":{
				"deps":[],
				"exports":"forge"
			},
			"libsodium":{
				"deps":[],
			},
			"sodium":{
				"deps":["libsodium"],
			},
			"victorjs":{
				"deps":[],
				"exports":"Victor"
			},
			"vecla":{
				"deps":[],
				"exports":"vec"
			},
			"kandinsky":{
				"deps":[],
				"exports":"kandinsky"
			},
			"chroma":{
				"deps":[],
				"exports":"chroma"
			},
			"tinycolor":{
				"deps":[],
				"exports":"tinycolor"
			},
			"jshint":{
				"deps":["lodash"],
				"exports":"JSHINT"
			},
			"mocha":{
				//"deps":[""],
				"exports":"mocha"
			},
			"chai":{
				"exports":"chai"
			},
			"chai-match":{
				"deps":["chai"],
			},
			"chai-jq":{
				"deps":["jquery","chai"],
			},
			"jasmine":{
				"deps":[],
			},
			"jasmine-html": {
				"deps":["jasmine"]
			},
			"jasmine-boot": {
				"deps":["jasmine","jasmine-html"]
			},
			"brython":{
				"deps":[],
				"exports":"__BRYTHON__"
			},
			"brython_stdlib":{
				"deps":["brython"],
			},
			"threejs":{
				"deps":[],
				"exports":"THREE"
			},
			"perljs":{
				"deps":[],
			},
			"qunit":{
				"deps":[],
				"exports":"Qunit"
			},
			"expect":{
				"deps":[],
				"exports":"expect"
			},
			"should":{
				"deps":[],
				"exports":"should"
			},
			"estraverse":{
				"deps":[],
				"exports":"estraverse"
			},
			"escodegen":{
				"deps":["estraverse","esutils"]
			},
			"esutils":{
				"deps":[],
				"exports":"esutils"
			},
			"esprima":{
				"deps":[],
			},
			"dukweb":{
				"deps":[],
				"exports":"Duktape"
			},
			"jslint":{
				"deps":[],
			},
			"acorn":{
				"deps":[],
			},
			"cdecl":{
				"deps":[],
			},
			"route-parser":{
				"deps":[],
			},
			"mustache":{
				"deps":[],
				"exports":"Mustache"
			},
			"handlebars":{
				"deps":[],
			},
			"nunjucks":{
				"deps":[],
			},
			"hoganjs":{
				"deps":[],
			},
			"doT":{
				"deps":[],
				"exports":"doT"
			},
			"bitset":{
				"deps":[],
				"exports":"BitSet"
			},
			"lzstring":{
				"deps":[],
				"exports":"LZString"
			},
			"base64string":{
				"deps":[],
			},
			"randomjs":{
				"deps":[],
			},
			"immutablejs":{
				"deps":[],
			},
			"mori":{
				"deps":[],
			},
			"buckets":{
				"deps":[],
			},
			"hashmapjs":{
				"deps":[],
			},
			"moment":{
				"deps":[],
				"exports":"moment"
			},
			"moment-timezone":{
				"deps":["moment"],
			},
			"moment-timezone-utils":{
				"deps":["moment-timezone"],
			},
			"date":{
				"deps":[]
			},
			"msjs":{
				"deps":[]
			},
			"fecha":{
				"deps":[]
			},
			"dayjs":{
				"deps":[]
			},
			"date-fns":{
				"deps":[]
			},
			"voca":{
				"deps":[]
			},
			"selecting":{
				"deps":[]
			},
			"underscore.string":{
				"deps":[/*"underscore"*//*not dependent on underscore*/]
			},
			"sprintf":{
				"deps":[],
				"exports":"sprintf"
			},
			"sugarjs":{
				"deps":[],
				"exports":"Sugar"
			},
			//"locutus":{}//todo//https://locutus.io/
			"he":{
				"deps":[]
			},
			"URI":{
				"deps":[],
				"exports":"URI"
			},
			"urljs":{
				"deps":[],
				"exports":"Url"
			},
			"url-pattern":{
				"deps":[],
			},
			"stringjs":{
				"deps":[],
			},
			"numeraljs":{
				"deps":[],
			},
			"chancejs":{
				"deps":[],
			},
			"accountingjs":{
				"deps":[],
			},
			"odometer":{
				"deps":[],
				"exports":"Odometer"
			},
			"fraction":{
				"deps":[],
			},
			"complex":{
				"deps":[],
			},
			"polynomial":{
				"deps":[],
			},
			"quaternion":{
				"deps":[],
			},
			"crypto":{
				"deps":[],
			},
			"ramda":{
				"deps":[],
			},
			"rambda":{
				"deps":[],
			},
			"mout":{
				"deps":[],
			},
			//"prelude":{"deps":[],},//in progress
			//"preludels":{"deps":[],}//in progress
			"storejs":{
				"deps":[],
			},
			"localforage":{
				"deps":[],
			},
		},
		"packages":[
			{
				"name":"dojo",
				"location":"vendor/dojo/1.16.3/dojo"
			}
		],

		"config":{
			"text":{
				//"env":"goja"
				"env":"xhr"
			}
		},
		"map":{
			"*":{
				//"jquery":"jquery-private"
				"datatables.net":"jquery.dataTables",                                                                                                                                     //https://datatables.net/forums/discussion/43169/unable-to-get-buttons-1-3-2-to-work-with-require-js-and-backbone-marionette
				"datatables.net-buttons":"dataTables.buttons"
			},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"xlsx":{
				"deps":[],
				"exports":"XLSX"//XLS too
			},
			"pdfjs":{//not gettings this to work
				"deps":[],
				"exports":"pdfjs-dist/build/pdf"//PDFNetworkStream"
			},
			"js-dos":{
				"deps":[],
				"exports":"Dos"
			},
			"jsnes":{
				"deps":[],
				"exports":"jsnes"
			},
			"jquery.player":{
				"deps":["jquery"],
				"exports":"jQuery.jPlayer"
			},
			"babylonjs":{
				"deps":[],
				"exports":"babylonjs"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"classjs":{
				"deps":[],
				"exports":"Class"
			},
			"class":{
				"deps":[],
				"exports":"Class"
			},

			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":["jspanelcss"],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"jquery.terminal":{
				"deps":["jquery","ascii_table",]
			},
			"wcwidth":{
				"deps":[]
			},
			"ascii_table":{
				"deps":["wcwidth"]
			},
			"autocomplete_menu":{
				"deps":["jquery","jquery.terminal"]
			},
			"unix_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"xml_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"browserify-shim":{
				"jquery":"global:jQuery"
			},
			"jquery.hotkeys":{
				"deps":["jquery"]//,
				//"exports":"jquery.hotkeys"
			},
			"jquery.easing":{
				"deps":["jquery"]
			},
			"kweui":{
				"deps":["jquery","jspanel"]
			},
			"ug-theme-default":{
				"deps":["jquery.unite","jquery.easing"]
			},
			"jquery.unite":{
				"deps":["jquery","jquery.easing"]
			},
			"bootstrap":{
				"deps":["jquery"]
			},
			"jquery.dataTables.css":{
				"deps":["jquery"]
			},
				//"deps":["jquery","jquery.dataTables.css"],//css!/medias/css/dataTable.css
			"jquery.dataTables":{
				"deps":[
					"jquery",
					"jquery.dataTables.css",//custom css injector
					//"css!./js/vendor/datatables/jquery.dataTables.min.css",
					//"css!./js/vendor/datatables/1.10.22/responsive.bootstrap.min.css",
					//"css!./js/vendor/datatables/1.10.22/dataTables.bootstrap.min.css",

				],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":[
					"jquery.dataTables",
					"jquery-private",
					/*
					"dataTables.buttons",
					"dataTables.responsive",
					"dataTables.rowGroup",
					"dataTables.searchPanes",
					"dataTables.keyTable",
					"buttons.colVis",
					"buttons.flash",
					"buttons.print",
					"buttons.html5",
					"dataTables.colReorder",
					"dataTables.autoFill",
					"dataTables.fixedColumns",
					"dataTables.rowReorder",
					"dataTables.fixedHeader",
					"dataTables.select",
					"dataTables.responsive",
					*/
				],
				"exports":"datatables"
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowGroup":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.searchPanes":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.keyTable":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.colVis":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.flash":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.print":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.html5":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.buttons":{
				//"deps":["jquery"],
				"deps":[
					"jquery",
					"datatables.net",
					//"buttons.colVis",
					//"buttons.flash",
					//"buttons.print",
					//"buttons.html5",
				],
			},
			"dataTables.colReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.autoFill":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedColumns":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedHeader":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.select":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"babel":{
				"deps":[],
				"exports":"Babel"
			},
			"backbone":{
				"deps":["underscore"],
				"exports":"Backbone"
			},
			"backbone.localstorage":{
				"deps":["underscore","backbone"],
				"exports":"Backbone.LocalStorage"
			},
			"es6":{
				"deps":["babel","text"]
			},
			"vue-router":{
				"deps":["vuejs"]
			},
			"d3-3.5.17":{
				//"deps":[],
				"exports":"d3"
			},
			"d3":{
				//"deps":[],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"console":{
				"deps":[],
				"exports":"console"
			},
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"svg":{
				"deps":[],
				"exports":"SVG"
			},
			"axios":{
				"deps":[],
				"exports":"axios"
			},
			"Phaser":{
				"exports":"Phaser"
			},
			"Phaser3220":{
			},
			"cubism":{
				"deps":["d3-3.5.17"],
				"exports":"cubism"
			},
			"LoremIpsum":{
				"deps":[],
				"exports":"LoremIpsum"
			},
			"bonsai":{
				"deps":[],
				"exports":"bonsai"
			},
			"carbon":{
				"deps":[],
				"exports":"C"
			},
			"svidget":{
				"deps":[],
				"exports":"svidget"
			},
			"pablo":{
				"deps":[],
				"exports":"Pablo"
			},
			"pts":{
				"deps":[],
				"exports":"Pts"
			},
			"pts":{
				"deps":[],
				"exports":"anime"
			},
			"twojs":{
				"deps":[],
				"exports":"Two"
			},
			"zdog":{
				"deps":[],
				"exports":"Zdog"
			},
			"pixijs":{
				"deps":[],
				"exports":"PIXI"
			},
			"mathjax":{
				"deps":[],
				"exports":"MathJax"
			},
			"p5":{
				"deps":[],
				"exports":"p5"
			},
			"terrajs":{
				"deps":[],
				"exports":"terra"
			},
			"bignumber":{
				"deps":[],
				"exports":"BigNumber"
			},
			"sylvester":{
				"deps":[],
				"exports":"Sylveste"
			},
			"numeric":{
				"deps":[],
				"exports":"numeric"
			},
			"jstat": {
				"deps":[],
				"exports": ["j$", "jStat"],
				"init":function(){//???
					return{
						"j$":j$,
						"jStat":jStat
					};
				}
			},
			"science":{
				"deps":[],
				"exports":"science"
			},
			"rift":{
				"deps":[],
				"exports":"Rift"
			},
			"lexer":{
				"deps":[],
				"exports":"Lexer"
			},
			"jison":{
				"deps":[],
				"exports":"Jison"
			},
			"xregexp":{
				"deps":[],
				"exports":"XRegExp"
			},
			"sjcl":{
				"deps":[],
				"exports":"sjcl"
			},
			"jsencrypt":{
				"deps":[],
				"exports":"JSEncrypt"
			},
			"openpgp":{
				"deps":[],
				"exports":"openpgp"
			},
			"forge":{
				"deps":[],
				"exports":"forge"
			},
			"libsodium":{
				"deps":[],
			},
			"sodium":{
				"deps":["libsodium"],
			},
			"victorjs":{
				"deps":[],
				"exports":"Victor"
			},
			"vecla":{
				"deps":[],
				"exports":"vec"
			},
			"kandinsky":{
				"deps":[],
				"exports":"kandinsky"
			},
			"chroma":{
				"deps":[],
				"exports":"chroma"
			},
			"tinycolor":{
				"deps":[],
				"exports":"tinycolor"
			},
			"jshint":{
				"deps":["lodash"],
				"exports":"JSHINT"
			},
			"mocha":{
				//"deps":[""],
				"exports":"mocha"
			},
			"chai":{
				"exports":"chai"
			},
			"chai-match":{
				"deps":["chai"],
			},
			"chai-jq":{
				"deps":["jquery","chai"],
			},
			"jasmine":{
				"deps":[],
			},
			"jasmine-html": {
				"deps":["jasmine"]
			},
			"jasmine-boot": {
				"deps":["jasmine","jasmine-html"]
			},
			"brython":{
				"deps":[],
				"exports":"__BRYTHON__"
			},
			"brython_stdlib":{
				"deps":["brython"],
			},
			"threejs":{
				"deps":[],
				"exports":"THREE"
			},
			"perljs":{
				"deps":[],
			},
			"qunit":{
				"deps":[],
				"exports":"Qunit"
			},
			"expect":{
				"deps":[],
				"exports":"expect"
			},
			"should":{
				"deps":[],
				"exports":"should"
			},
			"estraverse":{
				"deps":[],
				"exports":"estraverse"
			},
			"escodegen":{
				"deps":["estraverse","esutils"]
			},
			"esutils":{
				"deps":[],
				"exports":"esutils"
			},
			"esprima":{
				"deps":[],
			},
			"dukweb":{
				"deps":[],
				"exports":"Duktape"
			},
			"jslint":{
				"deps":[],
			},
			"acorn":{
				"deps":[],
			},
			"cdecl":{
				"deps":[],
			},
			"route-parser":{
				"deps":[],
			},
			"mustache":{
				"deps":[],
				"exports":"Mustache"
			},
			"handlebars":{
				"deps":[],
			},
			"nunjucks":{
				"deps":[],
			},
			"hoganjs":{
				"deps":[],
			},
			"doT":{
				"deps":[],
				"exports":"doT"
			},
			"bitset":{
				"deps":[],
				"exports":"BitSet"
			},
			"lzstring":{
				"deps":[],
				"exports":"LZString"
			},
			"base64string":{
				"deps":[],
			},
			"randomjs":{
				"deps":[],
			},
			"immutablejs":{
				"deps":[],
			},
			"mori":{
				"deps":[],
			},
			"buckets":{
				"deps":[],
			},
			"hashmapjs":{
				"deps":[],
			},
			"moment":{
				"deps":[],
				"exports":"moment"
			},
			"moment-timezone":{
				"deps":["moment"],
			},
			"moment-timezone-utils":{
				"deps":["moment-timezone"],
			},
			"date":{
				"deps":[]
			},
			"msjs":{
				"deps":[]
			},
			"fecha":{
				"deps":[]
			},
			"dayjs":{
				"deps":[]
			},
			"date-fns":{
				"deps":[]
			},
			"voca":{
				"deps":[]
			},
			"selecting":{
				"deps":[]
			},
			"underscore.string":{
				"deps":[/*"underscore"*//*not dependent on underscore*/]
			},
			"sprintf":{
				"deps":[],
				"exports":"sprintf"
			},
			"sugarjs":{
				"deps":[],
				"exports":"Sugar"
			},
			//"locutus":{}//todo//https://locutus.io/
			"he":{
				"deps":[]
			},
			"URI":{
				"deps":[],
				"exports":"URI"
			},
			"urljs":{
				"deps":[],
				"exports":"Url"
			},
			"url-pattern":{
				"deps":[],
			},
			"stringjs":{
				"deps":[],
			},
			"numeraljs":{
				"deps":[],
			},
			"chancejs":{
				"deps":[],
			},
			"accountingjs":{
				"deps":[],
			},
			"odometer":{
				"deps":[],
				"exports":"Odometer"
			},
			"fraction":{
				"deps":[],
			},
			"complex":{
				"deps":[],
			},
			"polynomial":{
				"deps":[],
			},
			"quaternion":{
				"deps":[],
			},
			"crypto":{
				"deps":[],
			},
			"ramda":{
				"deps":[],
			},
			"rambda":{
				"deps":[],
			},
			"mout":{
				"deps":[],
			},
			//"prelude":{"deps":[],},//in progress
			//"preludels":{"deps":[],}//in progress
			"storejs":{
				"deps":[],
				"exports":"localStorage",//still global
			},
			"storejs":{
				"deps":[],
			},
			"jstorage":{
				"deps":[],
				"exports":"$.jStorage"
			},
			"cross-storage.client":{
				"deps":[],
			},
			"cross-storage.hub":{
				"deps":[],
			},
			"basketjs":{
				"deps":[],
			},
			"bagjs":{
				"deps":[],
			},
			"basil":{
				"deps":[],
				"exports":"Basil"
			},
			"js-cookie":{
				"deps":[],
			},
			"dbjs":{
				"deps":[],
			},
			"lawnchair":{
				"deps":[],
				"exports":"Lawnchair"
			},
			"sqljs":{
				"deps":[],
			},
			"crumbsjs":{
				"deps":[],
			},
			"i18next":{
				"deps":[],
			},
			"babelfish":{
				"deps":[],
			},
			"ttag":{
				"deps":[],
			},
			"async":{
				"deps":[],
			},
			"q":{
				"deps":[],
			},
			"step":{
				"deps":[],
				"exports":"Step"
			},
			"contra":{
				"deps":[],
			},
			"bluebird":{
				"deps":[],
			},
			"bluebird.core":{
				"deps":[],
			},
			"objecteventtarget":{
				"deps":[],
				"exports":"ObjectEventTarget"
			},
			"sporadic":{
				"deps":[],
			},
			"director":{
				"deps":[],
				"exports":"Router"
			},
			"pagejs":{
				"deps":[],
			},
			"pathjs":{
				"deps":[],
				"exports":"Path"
			},
			"navaid":{
				"deps":[],
			},
			"dompurify":{
				"deps":[],
			},
			"js-xss":{
				"deps":[],
				"exports":"filterXSS"
			},
			"log":{
				"deps":[],
			},
			"conzole":{
				"deps":[],
				"exports":"conzole"
			},
			"consolelog":{
				"deps":[],
				"exports":"log"
			},
			"loglevel":{
				"deps":[],
			},
			"minilog":{
				"deps":[],
				"exports":"Minilog"
			},
			"bottleneck":{
				"deps":[],
			},
			"oauthsignature":{
				"deps":[],
				"exports":"oauthSignature"
			},
			"wretch":{
				"deps":[],
			},
			"tracking":{
				"deps":[],
				"exports":"tracking"
			},
			"tracking.eye":{
				"deps":["tracking"],
			},
			"tracking.face":{
				"deps":["tracking"],
			},
			"tracking.mouth":{
				"deps":["tracking"],
			},
			"convnetjs":{
				"deps":[],
				"exports":"convnetjs"
			},
			"brainjs":{
				"deps":[],
			},
			"synapses":{
				"deps":[],
				"exports":"NeuralNetwork"
			},
			"bowser":{
				"deps":[],
				"exports":"Bowser"
			},
			"benchmarkjs":{
				"deps":[],
			},
			"mprogress":{
				"deps":[],
				"exports":"Mprogress"
			},
			"nprogress":{
				"deps":[],
				"exports":"NProgress"
			},
			"spinjs":{
				"deps":[],
				"exports":"Spinner"
			},
			"progressjs":{
				"deps":[],
			},
			"progressbarjs":{
				"deps":[],
			},
			"pace":{
				"deps":[],
			},
			"topbar":{
				"deps":[],
				"exports":"topbar"
			},
			"nanobar":{
				"deps":[],
				"exports":"Nanobar"
			},
			"ladda":{
				"deps":["spinjs"],
				"exports":"Ladda"
			},
			"parsleyjs":{
				"deps":["jquery"],
			},
			"platform":{
				"deps":[],
			},
			"validator":{
				"deps":[],
			},
			"validatejs":{
				"deps":[],
				"exports":"FormValidator"
			},
			"isjs":{
				"deps":[],
			},
			"fieldval":{
				"deps":[],
				"exports":"FieldVal"
			},
			"keypress":{
				"deps":[],
				"exports":"keypress"
			},
			"keyboardjs":{
				"deps":[],
			},
			"zepto":{
				"deps":[],
			},
			"ionrangeslider":{
				"deps":["jquery"],
			},
			"fancyinput":{
				"deps":["jquery"],
			},
			"introjs":{
				"deps":[],
				"exports":"introJs"
			},
			"tether":{
				"deps":[],
			},
			"shepherdjs":{
				"deps":["tether"],
			},
			"chardin":{
				"deps":["jquery"],
			},
			"pageguide":{
				"deps":["jquery"],
				"exports":"tl"
			},
			"hopscotch":{
				"deps":[],
			},
			"jquery.joyride":{
				"deps":["jquery"],
				"exports":"jQuery.joyride"
			},
			"jquery.focusable":{
				"deps":["jquery"],
				//"exports":"jQuery.focusable"
				"exports":"Focusable"
			},
			"driverjs":{
				"deps":[],
			},
			"izitoast":{
				"deps":[],
			},
			"messanger":{
				"deps":["jquery"],
				"exports":"Messenger"
			},
			"noty":{
				"deps":[],
				//"exports":"Noty"
			},
			"pnotify":{
				"deps":[],
			},
			"toastr":{
				"deps":[],
			},
			"humanejs":{
				"deps":[],
			},
			"smokejs":{
				"deps":[],
				"exports":"smoke"
			},
			"notie":{
				"deps":[],
			},
		},
		"deps":[],//default dependencies
	});
});

