define(["module"],function(module){
	var modbase="www/kweutils/lib/";
	requirejs.config({
		"waitSeconds":0,
		//"baseUrl":baseurl,
		"paths": {
			"env":modbase+"goja/env",
			"promise":modbase+"goja/Promise.goja",
			"string":modbase+"goja/string",
			"alert":modbase+"goja/alert",
			"console":modbase+"goja/console",
			"window":modbase+"goja/window",
			"document":modbase+"goja/document",
			"idutils":modbase+"goja/idutils",
			"pathutils":modbase+"goja/pathutils",
			"pubsub":modbase+"goja/pubsub",
			"request":modbase+"goja/request",
			"class":modbase+"goja/class.goja",
			"classjs":modbase+"goja/class.goja",
			"colorutils":modbase+"goja/colorutils",
			"underscore":modbase+"vendor/underscore/underscore-min",
			"lodash":modbase+"vendor/lodash/lodash.min",
			"babel":modbase+"vendor/babel/babel.min",
			"text":modbase+"vendor/requirejs/require.text",
			"babel-plugin-transform-remove-strict-mode":modbase+"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":modbase+"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":modbase+"vendor/es6/es6",
			"jquery":modbase+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modbase+"vendor/jquery/jquery-private",
			"d3":modbase+"vendor/d3/3.5.17/d3.v3.min",//d3
			//"d3":modbase+"vendor/d3/4.13.0/d3",
			//"d3":modbase+"vendor/d3/4.13.0/d3",
			//"d3":modbase+"vendor/d3/4.13.0/d3.v4.min",//d3-3d
			//"d3":modbase+"vendor/d3/6.3.1/d3.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.1/d3-3d.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.2/d3-3d.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.3/d3-3d.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.5/d3-3d.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.7/d3-3d.min",
			//"d3-3d":modbase+"vendor/d3-3d/0.0.8/d3-3d.min",
			"d3-3d":modbase+"vendor/d3-3d/0.0.9/d3-3d.min",
			"d3-array":modbase+"vendor/d3-array/1.2.1/d3-array.min",
			"d3-collection":modbase+"vendor/d3-collection/1.0.4/d3-collection.min",
			"d3-dispatch":modbase+"vendor/d3-dispatch/1.0.3/d3-dispatch.min",
			"d3-request":modbase+"vendor/d3-request/1.0.6/d3-request.min",
			"d3-scale-chromatic":modbase+"vendor/d3-scale-chromatic/d3-scale-chromatic.v1.min",
			"d3-selection":modbase+"vendor/d3-selection/1.1.0/d3-selection.min",

			//"domino":modbase+"vendor/domino/blocks/index",
			"domino":modbase+"vendor/domino/index",
			"svg":modbase+"vendor/svg.js/3.0.16/svg",
			//"svg":modbase+"vendor/svg.js/3.0.16/svg.min",
			"zest":modbase+"vendor/zest/zest",
		},
		"config":{
			"text":{
				"env":"goja"
			}
		},
		"map":{
			"*":{
			},
			//"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"babel":{
				"deps":["string"],
				"exports":"Babel"
			},
			"string":{
				"deps":[],
				"exports":"String"
			},
			"es6":{
				"deps":["babel","text"]
			},  
			"console":{
				"deps":[],
				"exports":"console"
			},
			"domino":{
				"exports":"domino"
			},
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"jquery-private":{
				"deps":[]
			},
			"jquery":{
				"deps":["document","window"]
			},
			"d3":{
				//"deps":["window"],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"svg":{
				//"deps":["document","window"],
				//"exports":"svg"
				"exports":"SVG"
			},
		},
		"deps":[]//default dependencies
	});
});
