define(["module"],function(module){
	var baseurl=module.id.substring(0,module.id.lastIndexOf('/'));
	requirejs.config({
		//"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"waitSeconds":0,
		"baseUrl":baseurl,
		"paths": {
			"promise":"goja/Promise.goja",
			"string":"goja/string",
			"alert":"goja/alert",
			"console":"goja/console",
			"node":"goja/html/node",
			"window":"goja/html/window",
			"document":"goja/html/document",
			"html":"goja/html/html",
			"canvas":"goja/html/canvas",
			"ui":"goja/html/ui",
			"idutils":"goja/idutils",
			"pathutils":"goja/pathutils",
			"pubsub":"goja/pubsub",
			"request":"goja/request",
			"class":"goja/class.goja",
			"classjs":"goja/class.goja",
			"underscore":"vendor/underscore/underscore-min",
			"lodash":"vendor/lodash/lodash.min",
			"babel":"vendor/babel/babel.min",
			"text":"vendor/requirejs/require.text",
			"babel-plugin-transform-remove-strict-mode":"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":"vendor/es6/es6",
			"envjs":'vendor/envjs/platform/goja',
			"envjs_core":'vendor/envjs/platform/core',
			"envjs_timer":'vendor/envjs/timer',
		},
		"config":{
			"text":{
				"env":"goja"
			}
		},
		"map":{
			//"class":"classjs"
		},
		"shim": {
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"babel":{
				"deps":["string"],
				"exports":"Babel"
			},
			"string":{
				"deps":[],
				"exports":"String"
			},
			"es6":{
				"deps":["babel","text"]
			},  
			"console":{
				"deps":[],
				"exports":"console"
			},  
			"envjs":{
				"deps":[
					"console",
					"envjs_core",
					//"envjs_timer"
					//"envjs/platform/core",//envjs/console",
					//'envjs/platform/goja',
					//'envjs/window'
				],
				"exports":"Envjs"
			},  
			"envjs_timer":{
				"deps":["envjs_core"]
			},  
			"envjs_core":{
				"deps":[],
				"exports":"Envjs"
			},  


		},
		"deps":[]//default dependencies
	});
})
