define(["module"],function(module){
	//var baseUrl=module.id.substring(0,module.id.lastIndexOf('/'));
	//var baseUrl="./www/kweutils/lib";//module.id.substring(0,module.id.lastIndexOf('/'));
	var baseUrl="/lib";//module.id.substring(0,module.id.lastIndexOf('/'));
	//var baseUrl="/lib";//module.id.substring(0,module.id.lastIndexOf('/'));
	//var baseUrl="./www/kweutils/lib";//module.id.substring(0,module.id.lastIndexOf('/'));
	var modPath="";
	var GOJA=true;
	var dojoConfig = {
		//baseUrl:"./www/kweutils/",
		async: 0, // We want to make sure we are using the "modern" loader
		hasCache: {
			"host-node": 1, // Ensure we "force" the loader into Node.js mode
			"dom": 0 // Ensure that none of the code assumes we have a DOM
		},
		// While it is possible to use config-tlmSiblingOfDojo to tell the
		// loader that your packages share the same root path as the loader,
		// this really isn't always a good idea and it is better to be
		// explicit about our package map.
		packages: []
	};//will read?

	requirejs.config({
		//"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"waitSeconds":0,
		"baseUrl":baseUrl,
		"paths":{
			"env":modPath+"goja/env",
			"promise":modPath+"goja/Promise.goja",
			"string":modPath+"goja/string",
			"alert":modPath+"goja/alert",
			"console":modPath+"goja/console",
			"error":modPath+"goja/error",
			"window":modPath+"goja/window",
			"document":modPath+"goja/document",
			"idutils":modPath+"goja/idutils",
			"pathutils":modPath+"goja/pathutils",
			"pubsub":modPath+"goja/pubsub",
			"request":modPath+"goja/request",
			"class":modPath+"goja/class.goja",
			"classjs":modPath+"goja/class.goja",
			"colorutils":modPath+"goja/colorutils",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"babel":modPath+"vendor/babel/babel.min",
			"text":modPath+"vendor/requirejs/require.text",
			"babel-plugin-transform-remove-strict-mode":modPath+"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":modPath+"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":modPath+"vendor/es6/es6",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"d3":modPath+"vendor/d3/3.5.17/d3.v3.min",//d3
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3.v4.min",//d3-3d
			//"d3":modPath+"vendor/d3/6.3.1/d3.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.1/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.2/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.3/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.5/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.7/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.8/d3-3d.min",
			"d3-3d":modPath+"vendor/d3-3d/0.0.9/d3-3d.min",
			"d3-array":modPath+"vendor/d3-array/1.2.1/d3-array.min",
			"d3-collection":modPath+"vendor/d3-collection/1.0.4/d3-collection.min",
			"d3-dispatch":modPath+"vendor/d3-dispatch/1.0.3/d3-dispatch.min",
			"d3-request":modPath+"vendor/d3-request/1.0.6/d3-request.min",
			"d3-scale-chromatic":modPath+"vendor/d3-scale-chromatic/d3-scale-chromatic.v1.min",
			"d3-selection":modPath+"vendor/d3-selection/1.1.0/d3-selection.min",
			"domino":modPath+"vendor/domino/domino",
			//"domino":modPath+"vendor/domino/blocks/domino",
			"svg":modPath+"vendor/svg.js/3.0.16/svg",
			"zest":modPath+"vendor/zest/zest",
			"cyclejs":modPath+"vendor/cyclejs/cycle",
			"LoremIpsum":modPath+"vendor/lorem/lorem",
			//"xml2js":modPath+"vendor/xml2js/xml2js",
			"xml2js":modPath+"vendor/xml2js/index",
			//"dojo":"vendor/dojo/1.16.3/dojo/dojo",
			"vexflow":"vendor/vexflow/3.0.9/vexflow-min",
			"mathjs":modPath+"vendor/mathjs/8.1.1/math",
			"jison":modPath+"vendor/jison/jison",
			//"xregexp":modPath+"vendor/xregexp/3.2.0/xregexp-all.min",
			"xregexp":modPath+"vendor/xregexp/4.4.1/xregexp-all",
			"backbone":modPath+"vendor/backbone/1.4.0/backbone-min",
			"sjcl":modPath+"vendor/sjcl/1.0.8/sjcl",
			"jsencrypt":modPath+"vendor/jsencrypt/3.0.0/jsencrypt",
			"forge":modPath+"vendor/forge/0.10.0_amd/index.amd",
			//"crypto":modPath+"vendor/cryptojs/bower_components/crypto-js/crypto-js",//version slightly incompatible with goja (https://github.com/brix/crypto-js#320)
			"crypto":modPath+"vendor/cryptojs/3.1.9/crypto-js",//compatible with goja (https://github.com/brix/crypto-js#320)
			"victorjs":modPath+"vendor/victorjs/1.1.0/victor",
			"vecla":modPath+"vendor/vecla/vec.amd",
			"chroma":modPath+"vendor/chroma/2.1.0/chroma",
			"tinycolor":modPath+"vendor/tinycolor/1.4.2/tinycolor",
			"chai":modPath+"vendor/chai/4.2.0/chai.min",
			"should":modPath+"vendor/should/3.3.2/should.min",
			"escodegen":modPath+"vendor/escodegen/2.0.0/escodegen",
			"estraverse":modPath+"vendor/estraverse/5.2.0/estraverse",
			"esutils":modPath+"vendor/esutils/2.0.3/index",
			"esprima":modPath+"vendor/esprima/2.7.3/esprima",
			"mustache":modPath+"vendor/mustache/4.1.0/mustache.min",
			"handlebars":modPath+"vendor/handlebars/4.7.6/handlebars.amd.min",
			"nunjucks":modPath+"vendor/nunjucks/3.2.2/nunjucks.min",
			"hoganjs":modPath+"vendor/hoganjs/3.0.2/hogan.min.amd",
			"doT":modPath+"vendor/doT/1.1.1/doT",
			"bitset":modPath+"vendor/bitset/5.1.1/bitset",
			"lzstring":modPath+"vendor/lz-string/1.4.4/lz-string",
			"base64string":modPath+"vendor/lz-string/1.4.4/base64-string",
			"randomjs":modPath+"vendor/random-js/2.0.0/random.min",
			"immutablejs":modPath+"vendor/immutable-js/3.8.2/immutable.min",
			"mori":modPath+"vendor/mori/0.3.2/mori.min",
			"hashmapjs":modPath+"vendor/hashmapjs/2.4.0/hashmap",
			"buckets":modPath+"vendor/buckets-js/1.98.2/buckets.min",
			"moment":modPath+"vendor/momentjs/moment.min",
			"moment-timezone":modPath+"vendor/moment-timezone/0.5.32/moment-timezone",
			"moment-timezone-utils":modPath+"vendor/moment-timezone/0.5.32/moment-timezone-utils",
			"date":modPath+"vendor/date/0.3.3/date.min",
			"msjs":modPath+"vendor/msjs/index",
			"fecha":modPath+"vendor/fetcha/4.0.0/fecha.min",
			"date-fns":modPath+"vendor/date-fns/1.30.1/date_fns.min",
			"voca":modPath+"vendor/voca/1.4.0/voca.min",
			"underscore.string":modPath+"vendor/underscore.string/3.3.4/underscore.string.min",
			"sprintf":modPath+"vendor/sprintf/1.1.2/sprintf.min",
			"sugarjs":modPath+"vendor/sugarjs/2.0.4/sugar",
			//"locutus":modPath+"vendor/locutus/index",//todo//https://locutus.io/
			"he":modPath+"vendor/he/1.2.0/he",
			"url-pattern":modPath+"vendor/url-pattern/url-pattern",
			"stringjs":modPath+"vendor/stringjs/3.3.3/string.min",
			"numeraljs":modPath+"vendor/numeraljs/2.0.6/numeral",
			"chancejs":modPath+"vendor/chancejs/1.1.7/chance.es5",
			"accountingjs":modPath+"vendor/accountingjs/0.4.2/accounting.min",
			"fraction":modPath+"vendor/fractionjs/4.0.12/fraction.min",
			"complex":modPath+"vendor/complexjs/2.0.11/complex.min",
			"quaternion":modPath+"vendor/quaternion/1.1.0/quaternion.min",
			"polynomial":modPath+"vendor/polynomialjs/1.4.5/polynomial",
			"ramda":modPath+"vendor/ramda/0.25.0/ramda.min",
			"rambda":modPath+"vendor/rambda/0.27.1/ramda.min",
			"mout":modPath+"vendor/mout/1.2.2",
			"i18next":modPath+"vendor/i18next/19.8.4/i18next",
			"babelfish":modPath+"vendor/babelfish/1.2.0/babelfish",
			"benchmarkjs":modPath+"vendor/benchmarkjs/2.1.4/benchmark.amd",
			"platform":modPath+"vendor/platformjs/1.3.6/platform",
			"validator":modPath+"vendor/validatorjs/13.5.1/validator.min",
			//"":modPath+"",
		},

		"packages":[
			{
				"name":"dojo",
				"location":"vendor/dojo/1.16.3/dojo"
			}
		],

		"config":{
			"text":{
				"env":"goja"
			}
		},
		"map":{
			"*":{
			},
			//"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"babel":{
				"deps":["string"],
				"exports":"Babel"
			},
			"string":{
				"deps":[],
				"exports":"String"
			},
			"es6":{
				"deps":["babel","text"]
			},  
			"console":{
				"deps":[],
				"exports":"console"
			},
			/*
			"domino":{
				"exports":"domino"
			},
			*/
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"jquery-private":{
				"deps":[]
			},
			"jquery":{
				"deps":["document","window"]
			},
			"d3":{
				//"deps":["window"],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"svg":{
				//"deps":["document","window"],
				//"exports":"svg"
				"exports":"SVG"
			},
			"LoremIpsum":{
				"deps":[],
				"exports":"LoremIpsum"
			},
			//"xml2js":{}
			"jison":{
				"deps":[],
				"exports":"Jison"
			},
			"xregexp":{
				"deps":[],
				"exports":"XRegExp"
			},
			"backbone":{
				"deps":["underscore"],
				"exports":"Backbone"
			},
			"sjcl":{
				"deps":[],
				"exports":"sjcl"
			},
			"jsencrypt":{
				"deps":[],
				"exports":"JSEncrypt"
			},
			"forge":{
				"deps":[],
				"exports":"forge"
			},
			"victorjs":{
				"deps":[],
				"exports":"Victor"
			},
			"vecla":{
				"deps":[],
				"exports":"vec"
			},
			"kandinsky":{
				"deps":[],
				"exports":"kandinsky"
			},
			"chroma":{
				"deps":[],
				"exports":"chroma"
			},
			"tinycolor":{
				"deps":[],
				"exports":"tinycolor"
			},
			"chai":{
				"exports":"chai"
			},
			"should":{
				"deps":[],
				"exports":"should"
			},
			"estraverse":{
				"deps":[],
				"exports":"estraverse"
			},
			"escodegen":{
				"deps":["estraverse","esutils"]
			},
			"esutils":{
				"deps":[],
				"exports":"esutils"
			},
			"esprima":{
				"deps":[],
				//"exports":"esutils"
			},
			"mustache":{
				"deps":[],
				"exports":"Mustache"
			},
			"handlebars":{
				"deps":[],
				//"exports":"Mustache"
			},
			"nunjucks":{
				"deps":[],
				"exports":"nunjucks"
			},
			"hoganjs":{
				"deps":[],
				//"exports":"Mustache"
			},
			"doT":{
				"deps":[],
				"exports":"doT"
			},
			"bitset":{
				"deps":[],
				"exports":"BitSet"
			},
			"lzstring":{
				"deps":[],
				"exports":"LZString"
			},
			"base64string":{
				"deps":[],
				//"exports":""
			},
			"randomjs":{
				"deps":[],
				//"exports":""
			},
			"immutablejs":{
				"deps":[],
				//"exports":""
			},
			"mori":{
				"deps":[],
				//"exports":""
			},
			"buckets":{
				"deps":[],
				//"exports":""
			},
			"hashmapjs":{
				"deps":[],
				//"exports":""
			},
			"moment":{
				"deps":[],
				"exports":"moment"
			},
			"moment-timezone":{
				"deps":["moment"],
			},
			"moment-timezone-utils":{
				"deps":["moment-timezone"],
			},
			"date":{
				"deps":[],
			},
			"msjs":{
				"deps":[]
			},
			"fecha":{
				"deps":[]
			},
			"date-fns":{
				"deps":[]
			},
			"voca":{
				"deps":[]
			},
			"underscore.string":{
				"deps":["console"/*"underscore"*//*not dependent on underscore*/]
			},
			"sprintf":{
				"deps":[],
				"exports":"sprintf"
			},
			"sugarjs":{
				"deps":[],
				"exports":"Sugar"
			},
			//"locutus":{}//todo//https://locutus.io/
			"he":{
				"deps":[]
			},
			"url-pattern":{
				"deps":[],
			},
			"stringjs":{
				"deps":[],
			},
			"numeraljs":{
				"deps":[],
			},
			"chancejs":{
				"deps":[],
			},
			"accountingjs":{
				"deps":[],
			},
			"fraction":{
				"deps":[],
			},
			"complex":{
				"deps":[],
			},
			"polynomial":{
				"deps":[],
			},
			"quaternion":{
				"deps":[],
			},
			"crypto":{
				"deps":[],
			},
			"ramda":{
				"deps":[],
			},
			"rambda":{
				"deps":[],
			},
			"mout":{
				"deps":[],
			},
			"i18next":{
				"deps":[],
			},
			"babelfish":{
				"deps":[],
			},
			"benchmarkjs":{
				"deps":["lodash","platform"],
			},
			"platform":{
				"deps":[],
			},
			"validator":{
				"deps":[],
			},
		},
		"deps":[]//default dependencies
	});
});
