define(["module"],function(module){
	var baseUrl=module.id.substring(0,module.id.lastIndexOf('/'));
	var modPath="";
	requirejs.config({
		//"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"waitSeconds":0,
		"baseUrl":baseUrl,
		"paths": {
			"env":modPath+"goja/env",
			"promise":modPath+"goja/Promise.goja",
			"string":modPath+"goja/string",
			"alert":modPath+"goja/alert",
			"console":modPath+"goja/console",
			"window":modPath+"goja/window",
			"document":modPath+"goja/document",
			"idutils":modPath+"goja/idutils",
			"pathutils":modPath+"goja/pathutils",
			"pubsub":modPath+"goja/pubsub",
			"request":modPath+"goja/request",
			"class":modPath+"goja/class.goja",
			"classjs":modPath+"goja/class.goja",
			"colorutils":modPath+"goja/colorutils",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"babel":modPath+"vendor/babel/babel.min",
			"text":modPath+"vendor/requirejs/require.text",
			"babel-plugin-transform-remove-strict-mode":modPath+"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":modPath+"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":modPath+"vendor/es6/es6",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"d3":modPath+"vendor/d3/3.5.17/d3.v3.min",//d3
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3.v4.min",//d3-3d
			//"d3":modPath+"vendor/d3/6.3.1/d3.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.1/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.2/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.3/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.5/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.7/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.8/d3-3d.min",
			"d3-3d":modPath+"vendor/d3-3d/0.0.9/d3-3d.min",
			"d3-array":modPath+"vendor/d3-array/1.2.1/d3-array.min",
			"d3-collection":modPath+"vendor/d3-collection/1.0.4/d3-collection.min",
			"d3-dispatch":modPath+"vendor/d3-dispatch/1.0.3/d3-dispatch.min",
			"d3-request":modPath+"vendor/d3-request/1.0.6/d3-request.min",
			"d3-scale-chromatic":modPath+"vendor/d3-scale-chromatic/d3-scale-chromatic.v1.min",
			"d3-selection":modPath+"vendor/d3-selection/1.1.0/d3-selection.min",
			"domino":modPath+"vendor/domino/domino",
			//"domino":modPath+"vendor/domino/blocks/domino",
			"svg":modPath+"vendor/svg.js/3.0.16/svg",
			"zest":modPath+"vendor/zest/zest",
			"cyclejs":modPath+"vendor/cyclejs/cycle",
			"LoremIpsum":modPath+"vendor/lorem/lorem",
			//"xml2js":modPath+"vendor/xml2js/xml2js",
			"xml2js":modPath+"vendor/xml2js/index",
		},
		"config":{
			"text":{
				"env":"goja"
			}
		},
		"map":{
			"*":{
			},
			//"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"babel":{
				"deps":["string"],
				"exports":"Babel"
			},
			"string":{
				"deps":[],
				"exports":"String"
			},
			"es6":{
				"deps":["babel","text"]
			},  
			"console":{
				"deps":[],
				"exports":"console"
			},
			/*
			"domino":{
				"exports":"domino"
			},
			*/
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"jquery-private":{
				"deps":[]
			},
			"jquery":{
				"deps":["document","window"]
			},
			"d3":{
				//"deps":["window"],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"svg":{
				//"deps":["document","window"],
				//"exports":"svg"
				"exports":"SVG"
			},
			"LoremIpsum":{
				"deps":[],
				"exports":"LoremIpsum"
			},
			//"xml2js":{}
		},
		"deps":[]//default dependencies
	});
});


