define(["module"],function(module){
	requirejs.config({
		"baseUrl":"./lib",
		"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"paths": {
			"xlsx":"vendor/sheetjs/xlsx.full.min",//not getting this to work
			"pdfjs":"vendor/pdfjs/pdf",//not getting this to work
			"js-dos":"vendor/js-dos/js-dos",
			"jsnes":"vendor/jsnes/jsnes.min",
			"ace":"vendor/ace/ace",
			"babylonjs":"vendor/BabylonJS/babylon",
			"jquery":"vendor/jquery/jquery.3.5.1",
			"jquery-private":"vendor/jquery/jquery-private",
			"jspanelcss":"vendor/jspanel/jspanelcss",//add css
			"jspanel":"vendor/jspanel/jspanel",
			"jspanel.dock":"vendor/jspanel/jspanel.dock",
			"jspanel.contextmenu":"vendor/jspanel/jspanel.contextmenu",
			"jquery.terminal":"vendor/jqueryterminal/jquery.terminal-2.19.2",
			"jquery.player":"vendor/jquery.jplayer/jquery.jplayer.min",
			"wcwidth":"vendor/jqueryterminal/wcwidth",
			"ascii_table":"vendor/jqueryterminal/ascii_table",
			"autocomplete_menu":"vendor/jqueryterminal/autocomplete_menu",
			"unix_formatting":"vendor/jqueryterminal/unix_formatting",
			"xml_formatting":"vendor/jqueryterminal/xml_formatting",
			"classjs":"vendor/classjs/class.min",
			"css":"vendor/requirecss/css.min",
			"underscore":"vendor/underscore/underscore-min",
			"lodash":"vendor/lodash/lodash.min",
			"jquery.jsonForm":"vendor/jsonform/jsonform",
			"jsv":"vendor/jsv/jsv",
			"bootstrap":"vendor/bootstrap/3.3.7/bootstrap.min",
			"jquery.dataTables.css":"vendor/datatables/1.10.22/jquery.dataTables.css",
			"jquery.dataTables":"vendor/datatables/1.10.22/jquery.dataTables.min",
			"dataTables.bootstrap":"vendor/datatables/1.10.22/dataTables.bootstrap.min",
			"dataTables.responsive":"vendor/datatables/1.10.22/dataTables.responsive.min",
			"dataTables.rowGroup":"vendor/datatables/extensions/rowgroup/1.1.2/dataTables.rowGroup.min",
			"dataTables.searchPanes":"vendor/datatables/extensions/searchpanes/1.2.1/dataTables.searchPanes.min",
			"dataTables.keyTable":"vendor/datatables/extensions/keytable/2.5.3/dataTables.keyTable.min",
			"buttons.colVis":"vendor/datatables/extensions/buttons/1.6.5/buttons.colVis.min",
			"buttons.flash":"vendor/datatables/extensions/buttons/1.6.5/buttons.flash.min",
			"buttons.print":"vendor/datatables/extensions/buttons/1.6.5/buttons.print.min",
			"buttons.html5":"vendor/datatables/extensions/buttons/1.6.5/buttons.html5.min",
			"dataTables.buttons":"vendor/datatables/extensions/buttons/1.6.5/dataTables.buttons.min",
			"dataTables.colReorder":"vendor/datatables/extensions/colreorder/1.5.3/dataTables.colReorder.min",
			"dataTables.autoFill":"vendor/datatables/extensions/autofill/2.3.5/dataTables.autoFill.min",
			"dataTables.fixedColumns":"vendor/datatables/extensions/fixedcolumns/3.3.2/dataTables.fixedColumns.min",
			"dataTables.rowReorder":"vendor/datatables/extensions/rowreorder/dataTables.rowReorder.min",
			"dataTables.fixedHeader":"vendor/datatables/extensions/fixedheader/3.1.7/dataTables.fixedHeader.min",
			"dataTables.select":"vendor/datatables/extensions/select/1.3.1/dataTables.select.min",
			"dataTables.responsive":"vendor/datatables/extensions/responsive/2.2.6/dataTables.responsive.min",
			"ace":"vendor/ace/ace",
			"babel":"vendor/babel/babel.min",
			"spectrum":"vendor/spectrum/spectrum",
			"text":"vendor/requirejs/require.text",
			"backbone":"vendor/backbone/1.4.0/backbone-min",
			"babel-plugin-transform-remove-strict-mode":"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":"vendor/es6/es6",
		},
		"config":{
			"text":{
				//"env":"goja"
				"env":"xhr"
			}
		},
		"map":{
			"*":{
				//"jquery":"jquery-private"
				"datatables.net":"jquery.dataTables",                                                                                                                                     //https://datatables.net/forums/discussion/43169/unable-to-get-buttons-1-3-2-to-work-with-require-js-and-backbone-marionette
				"datatables.net-buttons":"dataTables.buttons"
			},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"xlsx":{
				"deps":[],
				"exports":"XLSX"//XLS too
			},
			"pdfjs":{//not gettings this to work
				"deps":[],
				"exports":"pdfjs-dist/build/pdf"//PDFNetworkStream"
			},
			"js-dos":{
				"deps":[],
				"exports":"Dos"
			},
			"jsnes":{
				"deps":[],
				"exports":"jsnes"
			},
			"jquery.player":{
				"deps":["jquery"],
				"exports":"jQuery.jPlayer"
			},
			"babylonjs":{
				"deps":[],
				"exports":"babylonjs"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"classjs":{
				"deps":[],
				"exports":"Class"
			},
			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":["jspanelcss"],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"jquery.terminal":{
				"deps":["jquery","ascii_table",]
			},
			"wcwidth":{
				"deps":[]
			},
			"ascii_table":{
				"deps":["wcwidth"]
			},
			"autocomplete_menu":{
				"deps":["jquery","jquery.terminal"]
			},
			"unix_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"xml_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"browserify-shim":{
				"jquery":"global:jQuery"
			},
			"jquery.hotkeys":{
				"deps":["jquery"]//,
				//"exports":"jquery.hotkeys"
			},
			"jquery.easing":{
				"deps":["jquery"]
			},
			"kweui":{
				"deps":["jquery","jspanel"]
			},
			"ug-theme-default":{
				"deps":["jquery.unite","jquery.easing"]
			},
			"jquery.unite":{
				"deps":["jquery","jquery.easing"]
			},
			"bootstrap":{
				"deps":["jquery"]
			},
			"jquery.dataTables.css":{
				"deps":["jquery"]
			},
				//"deps":["jquery","jquery.dataTables.css"],//css!/medias/css/dataTable.css
			"jquery.dataTables":{
				"deps":[
					"jquery",
					"jquery.dataTables.css",//custom css injector
					//"css!./js/vendor/datatables/jquery.dataTables.min.css",
					//"css!./js/vendor/datatables/1.10.22/responsive.bootstrap.min.css",
					//"css!./js/vendor/datatables/1.10.22/dataTables.bootstrap.min.css",

				],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":[
					"jquery.dataTables",
					"jquery-private",
					/*
					"dataTables.buttons",
					"dataTables.responsive",
					"dataTables.rowGroup",
					"dataTables.searchPanes",
					"dataTables.keyTable",
					"buttons.colVis",
					"buttons.flash",
					"buttons.print",
					"buttons.html5",
					"dataTables.colReorder",
					"dataTables.autoFill",
					"dataTables.fixedColumns",
					"dataTables.rowReorder",
					"dataTables.fixedHeader",
					"dataTables.select",
					"dataTables.responsive",
					*/
				],
				"exports":"datatables"
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowGroup":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.searchPanes":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.keyTable":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.colVis":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.flash":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.print":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.html5":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.buttons":{
				//"deps":["jquery"],
				"deps":[
					"jquery",
					"datatables.net",
					//"buttons.colVis",
					//"buttons.flash",
					//"buttons.print",
					//"buttons.html5",
				],
			},
			"dataTables.colReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.autoFill":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedColumns":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedHeader":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.select":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
				//"exports":"JSONForm"
				//"exports":"JSON"
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"babel":{
				"deps":[],
				"exports":"Babel"
			},
			"backbone":{
				"deps":["underscore"],
				"exports":"Backbone"
			},
			"es6":{
				"deps":["babel","text"]
			},
		},
		"deps":[],//default dependencies
	});
})
