define(["module"],function(module){
	var baseUrl="/kweutils/lib";
	var modPath="";
	var GOJA=true;
	var dojoConfig = {
		baseUrl:"./www/kweutils/",
		async: 0, // We want to make sure we are using the "modern" loader
		hasCache: {
			"host-node": 1, // Ensure we "force" the loader into Node.js mode
			"dom": 0 // Ensure that none of the code assumes we have a DOM
		},
		// While it is possible to use config-tlmSiblingOfDojo to tell the
		// loader that your packages share the same root path as the loader,
		// this really isn't always a good idea and it is better to be
		// explicit about our package map.
		packages: []
	};//will read?

	requirejs.config({
		"waitSeconds":0,
		//"baseUrl":"./lib",
		"baseUrl":baseUrl,
		"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"paths": {
			"env":modPath+"goja/env",//goja compat
			"Phaser":modPath+"vendor/phaser/3.50.0/phaser.min",
			"Phaser3220":modPath+"vendor/phaser/3.22.0/phaser-arcade-physics.min",
			"console":modPath+"goja/console",//goja compat
			"pubsub":modPath+"goja/pubsub",
			"pathutils":modPath+"goja/pathutils",
			"idutils":modPath+"goja/idutils",//goja compat
			"window":modPath+"goja/window",//domino wrap
			"document":modPath+"goja/document",//domino wrap
			"request":modPath+"goja/request",//goja compat
			"xlsx":modPath+"vendor/sheetjs/xlsx.full.min",//not getting this to work
			"colorutils":modPath+"goja/colorutils",
			"pdfjs":modPath+"vendor/pdfjs/pdf",//not getting this to work
			"js-dos":modPath+"vendor/js-dos/js-dos",
			"jsnes":modPath+"vendor/jsnes/jsnes.min",
			"ace":modPath+"vendor/ace/ace",
			"babylonjs":modPath+"vendor/BabylonJS/babylon",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"jspanelcss":modPath+"vendor/jspanel/jspanelcss",//add css
			"jspanel":modPath+"vendor/jspanel/jspanel",
			"jspanel.dock":modPath+"vendor/jspanel/jspanel.dock",
			"jspanel.contextmenu":modPath+"vendor/jspanel/jspanel.contextmenu",
			"jquery.terminal":modPath+"vendor/jqueryterminal/jquery.terminal-2.19.2",
			"jquery.player":modPath+"vendor/jquery.jplayer/jquery.jplayer.min",
			"wcwidth":modPath+"vendor/jqueryterminal/wcwidth",
			"ascii_table":modPath+"vendor/jqueryterminal/ascii_table",
			"autocomplete_menu":modPath+"vendor/jqueryterminal/autocomplete_menu",
			"unix_formatting":modPath+"vendor/jqueryterminal/unix_formatting",
			"xml_formatting":modPath+"vendor/jqueryterminal/xml_formatting",
			"class":modPath+"vendor/classjs/class.min",
			"classjs":modPath+"vendor/classjs/class.min",
			"css":modPath+"vendor/requirecss/css.min",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"jquery.jsonForm":modPath+"vendor/jsonform/jsonform",
			"jsv":modPath+"vendor/jsv/jsv",
			"bootstrap":modPath+"vendor/bootstrap/3.3.7/bootstrap.min",
			"jquery.dataTables.css":modPath+"vendor/datatables/1.10.22/jquery.dataTables.css",
			"jquery.dataTables":modPath+"vendor/datatables/1.10.22/jquery.dataTables.min",
			"dataTables.bootstrap":modPath+"vendor/datatables/1.10.22/dataTables.bootstrap.min",
			"dataTables.responsive":modPath+"vendor/datatables/1.10.22/dataTables.responsive.min",
			"dataTables.rowGroup":modPath+"vendor/datatables/extensions/rowgroup/1.1.2/dataTables.rowGroup.min",
			"dataTables.searchPanes":modPath+"vendor/datatables/extensions/searchpanes/1.2.1/dataTables.searchPanes.min",
			"dataTables.keyTable":modPath+"vendor/datatables/extensions/keytable/2.5.3/dataTables.keyTable.min",
			"buttons.colVis":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.colVis.min",
			"buttons.flash":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.flash.min",
			"buttons.print":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.print.min",
			"buttons.html5":modPath+"vendor/datatables/extensions/buttons/1.6.5/buttons.html5.min",
			"dataTables.buttons":modPath+"vendor/datatables/extensions/buttons/1.6.5/dataTables.buttons.min",
			"dataTables.colReorder":modPath+"vendor/datatables/extensions/colreorder/1.5.3/dataTables.colReorder.min",
			"dataTables.autoFill":modPath+"vendor/datatables/extensions/autofill/2.3.5/dataTables.autoFill.min",
			"dataTables.fixedColumns":modPath+"vendor/datatables/extensions/fixedcolumns/3.3.2/dataTables.fixedColumns.min",
			"dataTables.rowReorder":modPath+"vendor/datatables/extensions/rowreorder/dataTables.rowReorder.min",
			"dataTables.fixedHeader":modPath+"vendor/datatables/extensions/fixedheader/3.1.7/dataTables.fixedHeader.min",
			"dataTables.select":modPath+"vendor/datatables/extensions/select/1.3.1/dataTables.select.min",
			"dataTables.responsive":modPath+"vendor/datatables/extensions/responsive/2.2.6/dataTables.responsive.min",
			"ace":modPath+"vendor/ace/ace",
			"babel":modPath+"vendor/babel/babel.min",
			"spectrum":modPath+"vendor/spectrum/spectrum",
			"text":modPath+"vendor/requirejs/require.text",
			"backbone":modPath+"vendor/backbone/1.4.0/backbone-min",
			"backbone.localstorage":modPath+"vendor/backbone/plugins/Backbone.localStorage/2.0.0/backbone.localStorage",
			"babel-plugin-transform-remove-strict-mode":modPath+"vendor/babel/plugins/babel-plugin-transform-remove-strict-mode/index",
			"babel-plugin-module-resolver":modPath+"vendor/babel/plugins/babel-plugin-module-resolver-standalone/index",
			"es6":modPath+"vendor/es6/es6",
			"vuejs":modPath+"vendor/vuejs/2.6.12/vue.min",
			"vue-router":modPath+"vendor/vue-router/3.4.9/vue-router.min",
			"d3-3.5.17":modPath+"vendor/d3/3.5.17/d3.v3.min",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			//"d3":modPath+"vendor/d3/4.13.0/d3",
			"d3":modPath+"vendor/d3/4.13.0/d3.v4.min",
			//"d3":modPath+"vendor/d3/6.3.1/d3.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.1/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.2/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.3/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.5/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.7/d3-3d.min",
			//"d3-3d":modPath+"vendor/d3-3d/0.0.8/d3-3d.min",
			"d3-3d":modPath+"vendor/d3-3d/0.0.9/d3-3d.min",
			"d3-array":modPath+"vendor/d3-array/1.2.1/d3-array.min",
			"d3-collection":modPath+"vendor/d3-collection/1.0.4/d3-collection.min",
			"d3-dispatch":modPath+"vendor/d3-dispatch/1.0.3/d3-dispatch.min",
			"d3-request":modPath+"vendor/d3-request/1.0.6/d3-request.min",
			"d3-scale-chromatic":modPath+"vendor/d3-scale-chromatic/d3-scale-chromatic.v1.min",
			"d3-selection":modPath+"vendor/d3-selection/1.1.0/d3-selection.min",
			//"domino":modPath+"vendor/domino/blocks/index",
			"domino":modPath+"vendor/domino/domino",
			//https://stackoverflow.com/questions/18176737/svg-js-plugins-and-requirejs
			"svg":modPath+"vendor/svg.js/3.0.16/svg.min",
			"zest":modPath+"vendor/zest/zest",
			//"axios":modPath+"vendor/axios/0.12.0/axios.min",
			"axios":modPath+"vendor/axios/0.21.0/axios",
			"cyclejs":modPath+"vendor/cyclejs/cycle",
			"jsbasic":modPath+"vendor/jsbasic/basic",
			"jsbasic.tty":modPath+"vendor/jsbasic/tty",
			"jsbasic.dos":modPath+"vendor/jsbasic/dos",
			"jsbasic.lores":modPath+"vendor/jsbasic/lores",
			"jsbasic.hires":modPath+"vendor/jsbasic/hires",
			"jsbasic.bell":modPath+"vendor/jsbasic/bell",
			"jsbasic.keyboard":modPath+"vendor/jsbasic/keyboard",
			"cubism":modPath+"vendor/cubism/1.6.0/cubism.v1",
			"LoremIpsum":modPath+"vendor/lorem/lorem",
			"tonejs":modPath+"vendor/tonejs/14.7.74/Tone",
			"snap":modPath+"vendor/snap.svg/0.5.0/snap.svg-min",
			"bonsai":modPath+"vendor/bonsai/0.4.1/bonsai-0.4.1.min",
			"carbon":modPath+"vendor/carbon/C.min",
			/*
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.1",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.2",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.1.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.0",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.1",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.3",
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.3.0",
			"svidget":modPath+"vendor/svidget/0.3.5/svidget",
			 */
			"svidget":modPath+"vendor/svidget/0.3.0/svidget-0.2.2",
			"pablo":modPath+"vendor/pablo/0.5.2/pablo",
			"pts":modPath+"vendor/pts/0.9.1/pts",
			"anime":modPath+"vendor/anime/3.2.0/anime.min",
			"twojs":modPath+"vendor/twojs/1.1/two.min",
			"zdog":modPath+"vendor/zdog/1.1.2/zdog.dist.min",
			"pixijs":modPath+"vendor/pixijs/6.0.0/pixi.min",
			"tweenjs":modPath+"vendor/tweenjs/18.6.4/tween.amd",
			"mathjax":modPath+"vendor/mathjax/3.1.2/tex-mml-chtml",
			//"dojo":modPath+"vendor/dojo/1.16.3/dojo/dojo",
			//"dojo":modPath+"vendor/dojo/1.16.3/dojo/dojo",
			"vexflow":modPath+"vendor/vexflow/3.0.9/vexflow-min",
			"scribe":modPath+"vendor/scribe/js/scribe",
			"p5":modPath+"vendor/p5/1.2.0/p5",
			"mathjs":modPath+"vendor/mathjs/8.1.1/math",
			"terrajs":modPath+"vendor/terrajs/2.4.1/terra.min",
			"bignumber":modPath+"vendor/bignumber/bignumber",
			"sylvester":modPath+"vendor/sylvester/0.1.3/sylvester.src",
			"numeric":modPath+"vendor/numeric/1.2.6/numeric",
			"jstat":modPath+"vendor/jstat/1.9.4/jstat.min",
			"science":modPath+"vendor/science/1.9.3/science.v1",
			"rift":modPath+"vendor/rift/0.1.2/rift",
			"lexer":modPath+"vendor/lexer/1.7.8/lexer",
			//"jison":modPath+"vendor/jison/0.3.10/jison",
			"jison":modPath+"vendor/jison/jison",
			//"xregexp":modPath+"vendor/xregexp/3.2.0/xregexp-all.min",
			"xregexp":modPath+"vendor/xregexp/4.4.1/xregexp-all",
			"sjcl":modPath+"vendor/sjcl/1.0.8/sjcl",
			"jsencrypt":modPath+"vendor/jsencrypt/3.0.0/jsencrypt",
			"openpgp":modPath+"vendor/openpgp/4.10.9/openpgp",
			//"openpgp":modPath+"vendor/openpgp/4.10.9/lightweight/openpgp",//...ugh
			//"forge":modPath+"vendor/forge/0.10.0/forge",//still have to sort out amd
			"forge":modPath+"vendor/forge/0.7.0/forge.min",
			//"cryptojs":modPath+"vendor/cryptojs/index",//todo: create amd module (https://code.google.com/archive/p/crypto-js/downloads)
			"libsodium":modPath+"vendor/libsodiumjs/0.7.8/libsodium",
			"sodium":modPath+"vendor/libsodiumjs/0.7.8/libsodium-wrappers",
			"victorjs":modPath+"vendor/victorjs/1.1.0/victor",
			"vecla":modPath+"vendor/vecla/vec.amd",
			"kandinsky":modPath+"vendor/kandinskijs/1.3.0/kandinsky",
			"chroma":modPath+"vendor/chroma/2.1.0/chroma",
			//"jshint":modPath+"vendor/jshint/2.12.0/jshint",
			"jshint":modPath+"vendor/jshint/2.6.3/jshint",
			"mocha":modPath+"vendor/mocha/8.2.1/mocha",
			"chai":modPath+"vendor/chai/4.2.0/chai.min",
			"chai-match":modPath+"vendor/chai/chai-match/1.1.1/chai-match",
			"chai-jq":modPath+"vendor/chai/chai-jq/0.0.9/chai-jq.min",
			"jasmine":modPath+"vendor/jasmine/2.3.0/jasmine-core/jasmine",
			"jasmine-boot":modPath+"vendor/jasmine/2.3.0/jasmine-core/boot",
			"jasmine-html":modPath+"vendor/jasmine/2.3.0/jasmine-core/jasmine-html",
			"brython":modPath+"vendor/brython/3.8.0/brython.min",
			"brython_stdlib":modPath+"vendor/brython/3.8.0/brython_stdlib",
			"threejs":modPath+"vendor/threejs/r71/three",
			"qunit":modPath+"vendor/qunit/2.13.0/qunit",
			"tape":modPath+"vendor/tape/4.4.0/tape",
			"perljs":modPath+"vendor/perljs/perl",
			"sinon":modPath+"vendor/sinon/9.2.2/sinon-no-sourcemaps",
			"expect":modPath+"vendor/expect/0.3.1/expect",
			"should":modPath+"vendor/should/3.3.2/should.min",
			"escodegen":modPath+"vendor/escodegen/2.0.0/escodegen",
			"estraverse":modPath+"vendor/estraverse/5.2.0/estraverse",
			//"esutils":modPath+"vendor/esutils/2.0.3/utils",
			"esutils":modPath+"vendor/esutils/2.0.3/index",
			"esprima":modPath+"vendor/esprima/2.7.3/esprima",
			"dukweb":modPath+"vendor/dukweb/dukweb",
			"jslint":modPath+"vendor/jslint/jslint",
			"acorn":modPath+"vendor/acorn/7.3.1/acorn",
			"cdecl":modPath+"vendor/cdecl/1.0.0/cdecl",
			"route-parser":modPath+"vendor/route-parser/0.0.5/index",
			"mustache":modPath+"vendor/mustache/4.1.0/mustache.min",
			"handlebars":modPath+"vendor/handlebars/4.7.6/handlebars.amd.min",
			"testdata":modPath+"data",
		},
		"packages":[
			{
				"name":"dojo",
				"location":"vendor/dojo/1.16.3/dojo"
			}
		],

		"config":{
			"text":{
				//"env":"goja"
				"env":"xhr"
			}
		},
		"map":{
			"*":{
				//"jquery":"jquery-private"
				"datatables.net":"jquery.dataTables",                                                                                                                                     //https://datatables.net/forums/discussion/43169/unable-to-get-buttons-1-3-2-to-work-with-require-js-and-backbone-marionette
				"datatables.net-buttons":"dataTables.buttons"
			},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim": {
			"xlsx":{
				"deps":[],
				"exports":"XLSX"//XLS too
			},
			"pdfjs":{//not gettings this to work
				"deps":[],
				"exports":"pdfjs-dist/build/pdf"//PDFNetworkStream"
			},
			"js-dos":{
				"deps":[],
				"exports":"Dos"
			},
			"jsnes":{
				"deps":[],
				"exports":"jsnes"
			},
			"jquery.player":{
				"deps":["jquery"],
				"exports":"jQuery.jPlayer"
			},
			"babylonjs":{
				"deps":[],
				"exports":"babylonjs"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"classjs":{
				"deps":[],
				"exports":"Class"
			},
			"class":{
				"deps":[],
				"exports":"Class"
			},

			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":["jspanelcss"],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"jquery.terminal":{
				"deps":["jquery","ascii_table",]
			},
			"wcwidth":{
				"deps":[]
			},
			"ascii_table":{
				"deps":["wcwidth"]
			},
			"autocomplete_menu":{
				"deps":["jquery","jquery.terminal"]
			},
			"unix_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"xml_formatting":{
				"deps":["jquery","jquery.terminal"]
			},
			"browserify-shim":{
				"jquery":"global:jQuery"
			},
			"jquery.hotkeys":{
				"deps":["jquery"]//,
				//"exports":"jquery.hotkeys"
			},
			"jquery.easing":{
				"deps":["jquery"]
			},
			"kweui":{
				"deps":["jquery","jspanel"]
			},
			"ug-theme-default":{
				"deps":["jquery.unite","jquery.easing"]
			},
			"jquery.unite":{
				"deps":["jquery","jquery.easing"]
			},
			"bootstrap":{
				"deps":["jquery"]
			},
			"jquery.dataTables.css":{
				"deps":["jquery"]
			},
				//"deps":["jquery","jquery.dataTables.css"],//css!/medias/css/dataTable.css
			"jquery.dataTables":{
				"deps":[
					"jquery",
					"jquery.dataTables.css",//custom css injector
					//"css!./js/vendor/datatables/jquery.dataTables.min.css",
					//"css!./js/vendor/datatables/1.10.22/responsive.bootstrap.min.css",
					//"css!./js/vendor/datatables/1.10.22/dataTables.bootstrap.min.css",

				],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":[
					"jquery.dataTables",
					"jquery-private",
					/*
					"dataTables.buttons",
					"dataTables.responsive",
					"dataTables.rowGroup",
					"dataTables.searchPanes",
					"dataTables.keyTable",
					"buttons.colVis",
					"buttons.flash",
					"buttons.print",
					"buttons.html5",
					"dataTables.colReorder",
					"dataTables.autoFill",
					"dataTables.fixedColumns",
					"dataTables.rowReorder",
					"dataTables.fixedHeader",
					"dataTables.select",
					"dataTables.responsive",
					*/
				],
				"exports":"datatables"
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
				"exports":"datatables"
			},
			"dataTables.bootstrap":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowGroup":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.searchPanes":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.keyTable":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.colVis":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.flash":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.print":{
				"deps":["jquery","datatables.net"],
			},
			"buttons.html5":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.buttons":{
				//"deps":["jquery"],
				"deps":[
					"jquery",
					"datatables.net",
					//"buttons.colVis",
					//"buttons.flash",
					//"buttons.print",
					//"buttons.html5",
				],
			},
			"dataTables.colReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.autoFill":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedColumns":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.rowReorder":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.fixedHeader":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.select":{
				"deps":["jquery","datatables.net"],
			},
			"dataTables.responsive":{
				"deps":["jquery","datatables.net"],
			},
			"jquery.jqDock":{
				"deps":["jquery"],
				"exports":["jquery.jqDock"]
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"jspanel.contextmenu":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
				//"exports":"JSONForm"
				//"exports":"JSON"
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"babel":{
				"deps":[],
				"exports":"Babel"
			},
			"backbone":{
				"deps":["underscore"],
				"exports":"Backbone"
			},
			"backbone.localstorage":{
				"deps":["underscore","backbone"],
				"exports":"Backbone.LocalStorage"
			},
			"es6":{
				"deps":["babel","text"]
			},
			"vue-router":{
				"deps":["vuejs"]
			},
			"d3-3.5.17":{
				//"deps":[],
				"exports":"d3"
			},
			"d3":{
				//"deps":[],
				"exports":"d3"
			},
			"d3-3d":{
				"deps":["d3"]
			},
			"d3-array":{
				"deps":["d3"]
			},
			"d3-collection":{
				"deps":["d3"]
			},
			"d3-dispatch":{
				"deps":["d3"]
			},
			"d3-request":{
				"deps":["d3"]
			},
			"d3-scale-chromatic":{
				"deps":["d3"]
			},
			"d3-selection":{
				"deps":["d3"]
			},
			"console":{
				"deps":[],
				"exports":"console"
			},
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},
			"svg":{
				"deps":[],
				"exports":"SVG"
			},
			"axios":{
				"deps":[],
				"exports":"axios"
			},
			"Phaser":{
				"exports":"Phaser"
			},
			"Phaser3220":{
				//"exports":"Phaser"
			},
			"cubism":{
				"deps":["d3-3.5.17"],
				"exports":"cubism"
			},
			"LoremIpsum":{
				"deps":[],
				"exports":"LoremIpsum"
			},
			"bonsai":{
				"deps":[],
				"exports":"bonsai"
			},
			"carbon":{
				"deps":[],
				"exports":"C"
			},
			"svidget":{
				"deps":[],
				"exports":"svidget"
			},
			"pablo":{
				"deps":[],
				"exports":"Pablo"
			},
			"pts":{
				"deps":[],
				"exports":"Pts"
			},
			"pts":{
				"deps":[],
				"exports":"anime"
			},
			"twojs":{
				"deps":[],
				"exports":"Two"
			},
			"zdog":{
				"deps":[],
				"exports":"Zdog"
			},
			"pixijs":{
				"deps":[],
				"exports":"PIXI"
			},
			"mathjax":{
				"deps":[],
				"exports":"MathJax"
			},
			"p5":{
				"deps":[],
				"exports":"p5"
			},
			"terrajs":{
				"deps":[],
				"exports":"terra"
			},
			"bignumber":{
				"deps":[],
				"exports":"BigNumber"
			},
			"sylvester":{
				"deps":[],
				"exports":"Sylveste"
			},
			"numeric":{
				"deps":[],
				"exports":"numeric"
			},
			"jstat": {
				"deps":[],
				"exports": ["j$", "jStat"],
				"init":function(){//???
					return{
						"j$":j$,
						"jStat":jStat
					};
				}
			},
			"science":{
				"deps":[],
				"exports":"science"
			},
			"rift":{
				"deps":[],
				"exports":"Rift"
			},
			"lexer":{
				"deps":[],
				"exports":"Lexer"
			},
			"jison":{
				"deps":[],
				"exports":"Jison"
			},
			"xregexp":{
				"deps":[],
				"exports":"XRegExp"
			},
			"sjcl":{
				"deps":[],
				"exports":"sjcl"
			},
			"jsencrypt":{
				"deps":[],
				"exports":"JSEncrypt"
			},
			"openpgp":{
				"deps":[],
				"exports":"openpgp"
			},
			"forge":{
				"deps":[],
				"exports":"forge"
			},
			"libsodium":{
				"deps":[],
			},
			"sodium":{
				"deps":["libsodium"],
			},
			"victorjs":{
				"deps":[],
				"exports":"Victor"
			},
			"vecla":{
				"deps":[],
				"exports":"vec"
			},
			"kandinsky":{
				"deps":[],
				"exports":"kandinsky"
			},
			"chroma":{
				"deps":[],
				"exports":"chroma"
			},
			"jshint":{
				"deps":["lodash"],
				"exports":"JSHINT"
			},
			"mocha":{
				//"deps":[""],
				"exports":"mocha"
			},
			"chai":{
				"exports":"chai"
			},
			"chai-match":{
				"deps":["chai"],
				//"exports":"chaiMatch"
			},
			"chai-jq":{
				"deps":["jquery","chai"],
				//"exports":"chaiJq"
			},
			"jasmine":{
				//"deps":[""],
				//"exports":"jasmine"
			},
			"jasmine-html": {
				"deps":["jasmine"]
			},
			"jasmine-boot": {
				"deps":["jasmine","jasmine-html"]
				//"exports":"jasmine"
			},
			"brython":{
				"deps":[],
				"exports":"__BRYTHON__"
			},
			"brython_stdlib":{
				"deps":["brython"],
			},
			"threejs":{
				"deps":[],
				"exports":"THREE"
			},
			"perljs":{
				"deps":[],
				//"exports":""
			},
			"qunit":{
				"deps":[],
				"exports":"Qunit"
			},
			"expect":{
				"deps":[],
				"exports":"expect"
			},
			"should":{
				"deps":[],
				"exports":"should"
			},
			"estraverse":{
				"deps":[],
				"exports":"estraverse"
			},
			"escodegen":{
				"deps":["estraverse","esutils"]
			},
			"esutils":{
				"deps":[],
				"exports":"esutils"
			},
			"esprima":{
				"deps":[],
				//"exports":"esutils"
			},
			"dukweb":{
				"deps":[],
				"exports":"Duktape"
			},
			"jslint":{
				"deps":[],
				//"exports":"Duktape"
			},
			"acorn":{
				"deps":[],
				//"exports":"Duktape"
			},
			"cdecl":{
				"deps":[],
				//"exports":"Duktape"
			},
			"route-parser":{
				"deps":[],
				//"exports":"Duktape"
			},
			"mustache":{
				"deps":[],
				"exports":"Mustache"
			},
			"handlebars":{
				"deps":[],
				//"exports":"Mustache"
			},
		},
		"deps":[],//default dependencies
	});
});

